<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

<ItemGroup>
    <ProjectReference Include="..\Interfaces\ATAP.Utilities.StronglyTypedId.Interfaces.csproj" />
    <ProjectReference Include="..\Models\ATAP.Utilities.StronglyTypedId.Models.csproj" />
  </ItemGroup>

</Project>
