BeforeAll {
  if (-not (Get-Command Write-PSFMessage -ErrorAction SilentlyContinue)) {
    function global:Write-PSFMessage {
      param([Parameter(ValueFromRemainingArguments = $true)] $Rest)
    }
  }
  . "$PSScriptRoot\..\..\private\Get-AICoreInstructionBody.ps1"

  # The canonical path needs a real .ai tree (manifest + renderer + canonical source).
  # Rather than reproduce one, point at the live SharedVSCode worktree when it is present;
  # every canonical-path test skips cleanly when it is not (CI without the sibling repo).
  $script:SharedLive = @(
    'C:\Dropbox\whertzing\GitHub\SharedVSCode-wt-62-Sprint-0014-work-items'
    'C:\Dropbox\whertzing\GitHub\SharedVSCode'
  ) | Where-Object { Test-Path -LiteralPath (Join-Path $_ '.ai/tools/Render-AIAdapters.ps1') -PathType Leaf } |
    Select-Object -First 1
}

AfterAll {
  Remove-Item Function:\Write-PSFMessage -Force -ErrorAction SilentlyContinue
}

Describe 'Get-AICoreInstructionBody [private]' -Tag 'Unit' {

  Context 'canonical path (Task 14.60)' {
    BeforeEach {
      if (-not $script:SharedLive) {
        Set-ItResult -Skipped -Because 'no SharedVSCode worktree with a .ai tree is available'
      }
    }

    It 'composes the AGENTS core from canonical, not from AGENTS-base.md' {
      $result = Get-AICoreInstructionBody -SharedVSCodeRoot $script:SharedLive -Carrier AGENTS
      $result.Origin | Should -Be 'canonical'
      $result.SourcePath | Should -BeLike '*main-instructions.md'
      $result.RecordId | Should -Be 'ai.core.main-instructions.v1'
    }

    It 'emits AGENTS bytes identical to the legacy rendered base' {
      # The whole point of Task 14.60: dropping the intermediate file must not change one
      # byte of what the agents actually read.
      $legacy = Join-Path $script:SharedLive 'AGENTS-base.md'
      if (-not (Test-Path -LiteralPath $legacy -PathType Leaf)) {
        Set-ItResult -Skipped -Because 'the legacy AGENTS-base.md is no longer materialized'
        return
      }
      $generated = (Get-AICoreInstructionBody -SharedVSCodeRoot $script:SharedLive -Carrier AGENTS).Content
      $generated.TrimEnd() | Should -Be ((Get-Content -LiteralPath $legacy -Raw).TrimEnd())
    }

    It 'emits CLAUDE bytes identical to the legacy base' {
      $legacy = Join-Path $script:SharedLive 'CLAUDE-base.md'
      if (-not (Test-Path -LiteralPath $legacy -PathType Leaf)) {
        Set-ItResult -Skipped -Because 'the legacy CLAUDE-base.md is no longer materialized'
        return
      }
      $generated = (Get-AICoreInstructionBody -SharedVSCodeRoot $script:SharedLive -Carrier CLAUDE).Content
      $generated.TrimEnd() | Should -Be ((Get-Content -LiteralPath $legacy -Raw).TrimEnd())
    }

    It 'gives AGENTS the generated-wrapper header and CLAUDE the verbatim body' {
      $agents = (Get-AICoreInstructionBody -SharedVSCodeRoot $script:SharedLive -Carrier AGENTS).Content
      $claude = (Get-AICoreInstructionBody -SharedVSCodeRoot $script:SharedLive -Carrier CLAUDE).Content
      # AGENTS carries provenance; CLAUDE's manifest target is materialization 'copy'.
      $agents | Should -BeLike '*Generated by SharedVSCode .ai/tools/Render-AIAdapters.ps1.*'
      $agents | Should -BeLike '*SourceId: ai.core.main-instructions.v1*'
      $claude | Should -Not -BeLike '*Generated by SharedVSCode*'
    }

    It 'reports the canonical source hash' {
      $result = Get-AICoreInstructionBody -SharedVSCodeRoot $script:SharedLive -Carrier AGENTS
      $result.SourceSha256 | Should -Match '^[0-9a-f]{64}$'
    }

    It 'is deterministic across repeated calls' {
      $first = (Get-AICoreInstructionBody -SharedVSCodeRoot $script:SharedLive -Carrier AGENTS).Content
      $second = (Get-AICoreInstructionBody -SharedVSCodeRoot $script:SharedLive -Carrier AGENTS).Content
      $second | Should -Be $first
    }
  }

  Context 'legacy fallback and failure' {
    BeforeEach {
      $script:root = Join-Path $TestDrive ([guid]::NewGuid().ToString('N'))
      New-Item -ItemType Directory -Path $script:root -Force | Out-Null
    }

    It 'falls back to the legacy base when the worktree has no .ai tree' {
      # Older sprints, fixtures, and repos rendered from a pinned bundle still work.
      $legacy = Join-Path $script:root 'AGENTS-base.md'
      Set-Content -LiteralPath $legacy -Value "# legacy core`n" -Encoding UTF8
      $result = Get-AICoreInstructionBody -SharedVSCodeRoot $script:root -Carrier AGENTS -FallbackBaseFilePath $legacy
      $result.Origin | Should -Be 'legacy-base'
      $result.SourcePath | Should -Be $legacy
      $result.Content | Should -BeLike '*legacy core*'
    }

    It 'throws a directive error when neither canonical nor a legacy base is available' {
      { Get-AICoreInstructionBody -SharedVSCodeRoot $script:root -Carrier CLAUDE } |
        Should -Throw -ExpectedMessage '*Cannot build the CLAUDE core body*'
    }

    It 'throws when the supplied fallback does not exist' {
      { Get-AICoreInstructionBody -SharedVSCodeRoot $script:root -Carrier AGENTS `
          -FallbackBaseFilePath (Join-Path $script:root 'missing.md') } |
        Should -Throw -ExpectedMessage '*Cannot build the AGENTS core body*'
    }

    It 'rejects an unknown carrier' {
      { Get-AICoreInstructionBody -SharedVSCodeRoot $script:root -Carrier GEMINI } | Should -Throw
    }
  }
}
