//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATAP.Console.Console02 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UIResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ATAP.Console.Console02.UIResources", typeof(UIResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. PrettyPrint a GenerateCodeSignil.
        /// </summary>
        internal static string _1__PrettyPrint_a_GenerateCodeSignil {
            get {
                return ResourceManager.GetString("1. PrettyPrint a GenerateCodeSignil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Roundtrip a GenerateCodeSignil to Settings file and back.
        /// </summary>
        internal static string _2__Roundtrip_a_GenerateCodeSignil_to_Settings_file_and_back {
            get {
                return ResourceManager.GetString("2. Roundtrip a GenerateCodeSignil to Settings file and back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Run GenerateCodeAsync on a Settings file.
        /// </summary>
        internal static string _3__Run_GenerateCodeAsync_on_a_Settings_file {
            get {
                return ResourceManager.GetString("3. Run GenerateCodeAsync on a Settings file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99: Quit.
        /// </summary>
        internal static string _99__Quit {
            get {
                return ResourceManager.GetString("99: Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a number for a choice, Ctrl-C to Exit.
        /// </summary>
        internal static string Enter_a_number_for_a_choice__Ctrl_C_to_Exit {
            get {
                return ResourceManager.GetString("Enter a number for a choice, Ctrl-C to Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to first Progress Report message from input 1.
        /// </summary>
        internal static string first_Progress_Report_message_from_input_1 {
            get {
                return ResourceManager.GetString("first Progress Report message from input 1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You selected: {0}.
        /// </summary>
        internal static string You_selected___0_ {
            get {
                return ResourceManager.GetString("You selected: {0}", resourceCulture);
            }
        }
    }
}
