//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATAP.Console.Console2 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DebugResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DebugResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ATAP.Console.Console2.DebugResources", typeof(DebugResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in Program.Main: extend genericHostBuilder by calling extension method .ConfigureServices and adding to the DI Container a singleton instance of type IHostLifetime. the instance is of type {0}..
        /// </summary>
        internal static string AddingAnIHostLifetimeToGenericHostDI {
            get {
                return ResourceManager.GetString("AddingAnIHostLifetimeToGenericHostDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in Program.Main: Adding ConsoleLifetime to genericHostBuilder..
        /// </summary>
        internal static string AddingConsoleLifetimeTogenericHostBuilder {
            get {
                return ResourceManager.GetString("AddingConsoleLifetimeTogenericHostBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in Program.Main: create genericHostBuilder by calling static method CreateSpecificHostBuilder..
        /// </summary>
        internal static string CallingCreateSpecificHostBuilder {
            get {
                return ResourceManager.GetString("CallingCreateSpecificHostBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in Program.Main: initialEnvName from initialGenericHostConfigurationRoot ={0}..
        /// </summary>
        internal static string EnvNameInitial {
            get {
                return ResourceManager.GetString("EnvNameInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in Program.Main: envName from the final genericHostConfigurationRoot = {0}..
        /// </summary>
        internal static string EnvNameRunning {
            get {
                return ResourceManager.GetString("EnvNameRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in Service FunctionSelectorUI: Starting..
        /// </summary>
        internal static string FunctionSelectorUIServiceStarting {
            get {
                return ResourceManager.GetString("FunctionSelectorUIServiceStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in Program.Main: genericHostBuilder= {0}..
        /// </summary>
        internal static string GenericHostBuilderDetails {
            get {
                return ResourceManager.GetString("GenericHostBuilderDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in Program.Main: genericHostConfigurationRoot = {0}..
        /// </summary>
        internal static string GenericHostConfigurationRoot {
            get {
                return ResourceManager.GetString("GenericHostConfigurationRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in Program.Main: genericHost is starting..
        /// </summary>
        internal static string GenericHostStarting {
            get {
                return ResourceManager.GetString("GenericHostStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in Program.Main: SeriLog.Log.Logger.IsEnabled(Debug) is {0}..
        /// </summary>
        internal static string LoggerImportantCharacteristics {
            get {
                return ResourceManager.GetString("LoggerImportantCharacteristics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in Program.Main: Environment was not {0}, recreating the genericHostConfigurationRoot for Environment: {1}..
        /// </summary>
        internal static string RecreatingGenericHostConfigurationBuilderForEnvironment {
            get {
                return ResourceManager.GetString("RecreatingGenericHostConfigurationBuilderForEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in Program.Main: runtimeKind = {0}..
        /// </summary>
        internal static string RunTimeKindDetails {
            get {
                return ResourceManager.GetString("RunTimeKindDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in Program.Main: webHostBuilderToBuild from the genericHostConfigurationRoot = {0}..
        /// </summary>
        internal static string WebHostBuilderToBuildDetails {
            get {
                return ResourceManager.GetString("WebHostBuilderToBuildDetails", resourceCulture);
            }
        }
    }
}
