<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFrameworks>netstandard2.1;net5.0</TargetFrameworks>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <IsPackable>true</IsPackable>
  </PropertyGroup>


  <ItemGroup>
    <Folder Include="images\" />
    <Folder Include="svg\" />
  </ItemGroup>

    <!-- Include NuGet PackageReferences to the required DLLs for custom msbuild tasks-->
  <ItemGroup>

    <PackageReference Include="docfx.console">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>

    <PackageReference Include="Microsoft.Build.Utilities.Core" />
  </ItemGroup>
  <ProjectExtensions><VisualStudio><UserProperties /></VisualStudio></ProjectExtensions>


</Project>
