<#
.SYNOPSIS
    Instantiates AgentText records into tool-native adapter files.
.DESCRIPTION
    Accepts records returned by Import-AgentTextFromFiles and writes the adapter
    targets recorded in the manifest. The exporter supports copy and
    generated-wrapper materialization for the Sprint 0008 pilot and returns
    hash evidence for round-trip checks.
#>
function Export-AgentTextToFiles {
  [CmdletBinding(SupportsShouldProcess)]
  [OutputType([PSCustomObject])]
  param(
    [Parameter(Mandatory = $true, ValueFromPipeline = $true)]
    [ValidateNotNull()]
    [PSCustomObject] $AgentText,

    [Parameter(Mandatory = $true)]
    [ValidateNotNullOrEmpty()]
    [string] $TargetRoot
  )

  begin {
    $fn = 'Export-AgentTextToFiles'
    $mn = 'ATAP.Utilities.RulesManagement.PowerShell'
    Write-PSFMessage -FunctionName $fn -ModuleName $mn -Level Debug -Message 'Function started'

    function Get-AgentTextRenderedHash {
      param([Parameter(Mandatory = $true)][string] $Path)

      $bytes = [System.IO.File]::ReadAllBytes((Resolve-Path -LiteralPath $Path).Path)
      $sha = [System.Security.Cryptography.SHA256]::Create()
      try {
        $hash = ([System.BitConverter]::ToString($sha.ComputeHash($bytes))).Replace('-', '').ToLowerInvariant()
      }
      finally {
        $sha.Dispose()
      }

      [PSCustomObject]@{
        Sha256 = $hash
        Bytes  = $bytes.Length
      }
    }

    function New-AgentTextGeneratedWrapper {
      param(
        [Parameter(Mandatory = $true)][PSCustomObject] $Record,
        [Parameter(Mandatory = $true)][PSCustomObject] $Target
      )

      $header = @(
        '<!--'
        'Generated by Export-AgentTextToFiles.'
        'Do not edit this adapter directly; update AgentText/RRSBS source data instead.'
        "SourceId: $($Record.SourceId)"
        "SourceSha256: $($Record.BodySha256)"
        "Materialization: $($Target.Materialization)"
        '-->'
        ''
      ) -join "`r`n"

      if ($Target.Path -ieq 'AGENTS.md') {
        return "# AGENTS.md instructions for ATAP shared repositories`r`n`r`n$header$($Record.BodyText.TrimStart())"
      }

      return $header + $Record.BodyText.TrimStart()
    }
  }

  process {
    try {
      $targetRootFull = [System.IO.Path]::GetFullPath($TargetRoot)
      $results = [System.Collections.Generic.List[object]]::new()
      foreach ($target in @($AgentText.AdapterTargets)) {
        $targetPath = if ([System.IO.Path]::IsPathRooted([string]$target.Path)) {
          [string]$target.Path
        }
        else {
          Join-Path -Path $targetRootFull -ChildPath ([string]$target.Path)
        }

        $directory = Split-Path -Path $targetPath -Parent
        if (-not (Test-Path -LiteralPath $directory -PathType Container)) {
          New-Item -ItemType Directory -Path $directory -Force | Out-Null
        }

        $content = switch ([string]$target.Materialization) {
          'copy' { [string]$AgentText.BodyText; break }
          'generated-wrapper' { New-AgentTextGeneratedWrapper -Record $AgentText -Target $target; break }
          default { throw "Export-AgentTextToFiles does not yet support materialization '$($target.Materialization)' for $($target.Path)" }
        }

        $normalized = $content -replace "`r?`n", "`r`n"
        if (-not $normalized.EndsWith("`r`n", [StringComparison]::Ordinal)) {
          $normalized += "`r`n"
        }

        $action = 'unchanged'
        $existing = if (Test-Path -LiteralPath $targetPath -PathType Leaf) {
          [System.IO.File]::ReadAllText($targetPath, [System.Text.Encoding]::UTF8)
        }
        else {
          $null
        }

        if ($existing -cne $normalized) {
          $action = 'written'
          if ($PSCmdlet.ShouldProcess($targetPath, 'write AgentText adapter')) {
            [System.IO.File]::WriteAllText($targetPath, $normalized, [System.Text.UTF8Encoding]::new($false))
          }
        }

        $hash = if (Test-Path -LiteralPath $targetPath -PathType Leaf) {
          Get-AgentTextRenderedHash -Path $targetPath
        }
        else {
          $null
        }

        $results.Add([PSCustomObject]@{
          SourceId        = $AgentText.SourceId
          Path            = $target.Path
          Materialization = $target.Materialization
          Action          = $action
          Sha256          = if ($hash) { $hash.Sha256 } else { $null }
          Bytes           = if ($hash) { $hash.Bytes } else { $null }
        })
      }

      return [PSCustomObject]@{
        SourceId = $AgentText.SourceId
        TargetRoot = $targetRootFull
        Results = $results
      }
    }
    catch {
      Write-PSFMessage -FunctionName $fn -ModuleName $mn -Level Error -Message $_.Exception.Message
      throw
    }
  }

  end {
    Write-PSFMessage -FunctionName $fn -ModuleName $mn -Level Debug -Message 'Function completed'
  }
}
