<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <EnableDefaultItems>false</EnableDefaultItems>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <IsPackable>true</IsPackable>
    <MajorVersion>0</MajorVersion>
    <MinorVersion>1</MinorVersion>
    <PatchVersion>0</PatchVersion>
    <PackageLifeCycleStage>Development</PackageLifeCycleStage>
    <PackageLabel>Alpha</PackageLabel>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="StringConstants\ATAP.Utilities.Secrets.StringConstants.csproj" />
    <ProjectReference Include="Enumerations\ATAP.Utilities.Secrets.Enumerations.csproj" />
    <ProjectReference Include="Interfaces\ATAP.Utilities.Secrets.Interfaces.csproj" />
    <ProjectReference Include="Model\ATAP.Utilities.Secrets.Model.csproj" />
    <ProjectReference Include="Shim\ATAP.Utilities.Secrets.Shim.csproj" />
  </ItemGroup>

  <!-- Packages and projects to implement IL Weaving using Fody during the build process -->
  <!-- MethodBoundaryAspect.Fody is injected by Directory.Build.targets; do not repeat here. -->
  <ItemGroup>
    <ProjectReference Include="..\ATAP.Utilities.ETW\ATAP.Utilities.ETW.csproj" />
  </ItemGroup>

</Project>
