<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageVersion>0.1.1</PackageVersion>
    <Version>0.1.1</Version>
    <OutputType>Library</OutputType>
    <EnableDefaultItems>false</EnableDefaultItems>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <IsPackable>true</IsPackable>
    <MajorVersion>0</MajorVersion>
    <MinorVersion>1</MinorVersion>
    <PatchVersion>1</PatchVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="StringConstants\ATAP.Utilities.Secrets.StringConstants.csproj" />
    <ProjectReference Include="Enumerations\ATAP.Utilities.Secrets.Enumerations.csproj" />
    <ProjectReference Include="Interfaces\ATAP.Utilities.Secrets.Interfaces.csproj" />
    <ProjectReference Include="Model\ATAP.Utilities.Secrets.Model.csproj" />
  </ItemGroup>
  <!-- Packages and projects to implement IL Weaving using Fody during the build process -->
  <!-- MethodBoundaryAspect.Fody is injected by Directory.Build.targets; do not repeat here. -->
  <ItemGroup>
    <ProjectReference Include="..\ATAP.Utilities.ETW\ATAP.Utilities.ETW.csproj" />
  </ItemGroup>
</Project>