# Prettier configuration file in YAML format
printWidth: 120 # Maximum line length
tabWidth: 2 # Number of spaces per indentation level
trailingComma: all # Trailing commas where valid in ES5 (objects, arrays, etc.)
semi: true # Print semicolons at the ends of statements
overrides:
  - files: "*.ts" # Apply these rules to TypeScript files
    options:
      printWidth: 120 # Override print width for TypeScript files
      singleQuote: true # Use single quotes instead of double quotes

