<Project>

  <!-- import the non-default targets files -->

  <!-- MSBuild Community Tasks — optional, comment out if MSBuildTasks package not present -->
  <!-- <Import Project="$(MSBuildCommunityTasksPath)\MSBuildTasks.Targets" /> -->
  <!-- BuildTooling custom tasks: GetVersion / UpdateVersion / SetVersion + PublishAfterBuild -->
  <Import Project="$(ATAPUtilitiesBuildToolingTargetsPath)\ATAP.Utilities.BuildTooling.targets" />

  <!-- ItemGroup for automatically generating Designer files and embedding resources in an assembly -->
  <!-- Attribution: https://stackoverflow.com/questions/46584499/how-to-add-a-glob-for-resx-files-for-new-sdk-csproj-file -->
  <!-- ToDo: Make the Generator Value conditional, if run under VS, use PublicResXFileCodeGenerator or ResXFileCodeGenerator.
          if not run under CS (for example dotnet build or dotnet msbuild, use resgen.exe)
  -->
  <ItemGroup>
    <Resx Include="**\*.resx" />
    <EmbeddedResource Include="**\*.resource" />

    <!--
    <Compile Include="**\*.Designer.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>$([System.String]::Copy('%(FileName)').Replace('.Designer', '.resx'))</DependentUpon>
    </Compile>
        -->
  </ItemGroup>

  <!-- It appears that there is no solution for building/embedding resources in the dotnet toolchain for V5.0-->
  <!--
  </ItemGroup>
  <Target Name="Resources" BeforeTargets="Compile">
    <Message Condition="'$(ATAPBuildToolingConfiguration)'=='Debug'" Text="_TargetFrameworks = @(_TargetFrameworks -> '%(Identity)')" />
    <ItemGroup>
      <_TargetFrameworks Include="$(TargetFrameworks.Split(';'))" />
    </ItemGroup>
    <Message Condition="'$(ATAPBuildToolingConfiguration)'=='Debug'" Text="_TargetFrameworks = @(_TargetFrameworks -> '%(Identity)')" />
    <ItemGroup>
      <_IntermediateOutputPathPlusTargetFramework Include="@(_TargetFrameworks -> '$(IntermediateOutputPath)%(Identity)')" />
    </ItemGroup>
    <Message Condition="'$(ATAPBuildToolingConfiguration)'=='Debug'" Text="testStr =  'testStr'" />
    <Message Condition="'$(ATAPBuildToolingConfiguration)'=='Debug'" Text="testStrReplace =  $([System.String]::Copy('testStr').Replace('test','replace'))" />
    <Message Condition="'$(ATAPBuildToolingConfiguration)'=='Debug'" Text="_IntermediateOutputPathPlusTargetFramework = @(_IntermediateOutputPathPlusTargetFramework->'%(Identity)')" />
    -->
  <!-- ToDo: Add Runtime Identifier -->
  <!--
    <Message Condition="'$(ATAPBuildToolingConfiguration)'=='Debug'" Text="ListOfResxFiles = @(Resx)" />
    <Message Condition="'$(ATAPBuildToolingConfiguration)'=='Debug'" Text="ListOfDesignerFiles = @(Resx -> '%(Identity)')" />
    <Message Condition="'$(ATAPBuildToolingConfiguration)'=='Debug'" Text="ListOfDesignerFiles = @(Resx -> $([System.String]::Copy('%(Resx.Identity)').Replace('resx','Generated.cs'))" />
    <Message Condition="'$(ATAPBuildToolingConfiguration)'=='Debug'" Text="OutputResources = @(Resx->'$(IntermediateOutputPath)%(TargetFrameworks)%(FileName).resources')" />
    <Message Condition="'$(ATAPBuildToolingConfiguration)'=='Debug'" Text="OutputResources = @($([System.String]::Copy('%(Resx.Identity)').Replace('.resx', '.resource')))" />
    <PropertyGroup>
    <SingleResxFile>Resources/DebugMessages.resx</SingleResxFile>
    <SingleResourceFile>Resources/ATAP.Services.GenerateProgram.DebugMessages.resources</SingleResourceFile>
    <SingleStronglyTypedFilename>Resources/ATAP.Services.GenerateProgram.DebugMessages.GeneratedStronglyTypedFile.cs</SingleStronglyTypedFilename>
    <StronglyTypedNamespace>ATAP.Services.GenerateProgram</StronglyTypedNamespace>
    <StronglyTypedClassName>DebugMessages</StronglyTypedClassName>
    </PropertyGroup>
    <Message Condition="'$(ATAPBuildToolingConfiguration)'=='Debug'" Text="SingleResxFile = $(SingleResxFile); SingleResourceFile = $(SingleResourceFile); SingleStronglyTypedFilename = $(SingleStronglyTypedFilename)" />
    <GenerateResource Condition="Exists('$(SingleResxFile)')" Sources="$(SingleResxFile)" OutputResources="$(SingleResourceFile)" PublicClass="true" StronglyTypedLanguage="C#"
       StronglyTypedNamespace = '$(StronglyTypedNamespace)'
       StronglyTypedClassName = '$(StronglyTypedClassName)'
       StronglyTypedFilename = '$(SingleStronglyTypedFilename)'
       >
      <Output TaskParameter="OutputResources" ItemName="Resources" />
      <Output TaskParameter="FilesWritten" ItemName="FileWrites" />
    </GenerateResource>
    <Message Condition="'$(ATAPBuildToolingConfiguration)'=='Debug'" Text="OutputResources = @(Resources)" />
    <Message Condition="'$(ATAPBuildToolingConfiguration)'=='Debug'" Text="FilesWritten = @(FileWrites)" />
  </Target>
  -->

  <!-- when creating Console programs or services, if they dynamically load Plugins, define where the Plugins subdirectory is located -->
  <PropertyGroup>
    <PluginsRelativeDir Condition="$(PluginsRelativeDir) == '' Or $(PluginsRelativeDir) == '*Undefined*'">Plugins\</PluginsRelativeDir>
    <PluginsDir Condition="$(PluginsDir) == '' Or $(PluginsDir) == '*Undefined*'">$(OutputPath)$(PluginsRelativeDir)</PluginsDir>
  </PropertyGroup>


  <!-- Solution-wide, copy newer .json settings files that exist in the project directory into the output directory -->
  <PropertyGroup>
    <PrepareForRunDependsOn>$(PrepareForRunDependsOn);CopyJSONSettingsFilesToOutputDirectory</PrepareForRunDependsOn>
  </PropertyGroup>
  <ItemGroup>
    <JsonSettingsFiles Include="*.json" Condition="$([System.Text.RegularExpressions.Regex]::IsMatch(%(Filename), '[Ss]ettings.*json$'))" />
  </ItemGroup>
  <Target Name="CopyJSONSettingsFilesToOutputDirectory">
    <Copy SourceFiles="@(JsonSettingsFiles)" DestinationFolder="$(OutDir)" />
  </Target>

  <!-- Targets for multiframework and multiple Runtime Identifiers publishing courtesy of
    this stackoverflow answer https://stackoverflow.com/questions/43947599/how-to-publish-for-all-target-frameworks
    this GIST:https://gist.github.com/dasMulli/b14026437468ce4b56ef93e010f24a36
    and this issue: https://github.com/dotnet/sdk/issues/9363
   -->

  <Target Name="PublishProjectForAllRIDsIfTargetFrameworkSet" Condition=" '$(TargetFramework)' != '' and '$(RuntimeIdentifiers)' != '' and '$(RuntimeIdentifier)' == ''  ">
    <ItemGroup>
      <_PublishRuntimeIdentifier Include="$(RuntimeIdentifiers)" />
    </ItemGroup>
    <MSBuild Projects="$(MSBuildProjectFile)" Targets="PublishAll" Properties="TargetFramework=$(TargetFramework);RuntimeIdentifier=%(_PublishRuntimeIdentifier.Identity)" />
  </Target>

  <Target Name="PublishProjectForAllFrameworksIfFrameworkUnset" Condition=" '$(TargetFramework)' == '' ">
    <ItemGroup>
      <_PublishFramework Include="$(TargetFrameworks)" />
    </ItemGroup>
    <MSBuild Projects="$(MSBuildProjectFile)" Targets="PublishAll" Properties="TargetFramework=%(_PublishFramework.Identity)" />
  </Target>

  <Target Name="PublishAll" DependsOnTargets="PublishProjectIfFrameworkSet;PublishProjectForAllRIDsIfTargetFrameworkSet;PublishProjectForAllFrameworksIfFrameworkUnset" />
  <Target Name="PublishProjectIfFrameworkSet" DependsOnTargets="Publish" Condition=" '$(TargetFramework)' != '' " />

  <!-- Microsoft Source Link for every project -->
  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <!-- Include Roslyn Code Analysis for every project -->
  <!-- FxCopAnalyzers package has been deprecated in favor of 'Microsoft.CodeAnalysis.NetAnalyzers', hence this is now commented out -->
  <!--
  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.FxCopAnalyzers"></PackageReference>
  </ItemGroup>
  -->

  <!-- Central Package Management is now handled in Directory.Packages.props -->
  <!-- See: https://learn.microsoft.com/en-us/nuget/consume-packages/central-package-management -->

  <!-- Include Documentation generation for every project, but only when built with Net47, as docfx 2.51.2  is only supported on net47 -->
  <!--
  <ItemGroup Condition="$(TargetFramework.Contains('net47'))>
    <PackageReference Include="docfx" />
    <Folder Include="Documentation\" />
    <PackageReference Update="docfx" Version="2.51.2" />
  </ItemGroup>
  -->
</Project>
