<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <DefaultNamespace>ATAP.Utilities.ManimVideoGenerator</DefaultNamespace>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <!-- StringConstants used in this library -->
    <ProjectReference Include="..\StringConstants\ATAP.Utilities.ManimVideoGenerator.StringConstants.csproj" PrivateAssets="all" />
    <!-- Enumerations used in this library -->
    <ProjectReference Include="..\Enumerations\ATAP.Utilities.ManimVideoGenerator.Enumerations.csproj"  PrivateAssets="all" />
    <!-- Interfaces implemented by models in this library -->
    <ProjectReference Include="..\Interfaces\ATAP.Utilities.ManimVideoGenerator.Interfaces.csproj" PrivateAssets="all" />
  </ItemGroup>

  <!-- Packages and projects to implement IL Weaving using Fody during the build process -->
  <ItemGroup>
    <!-- Packages to implement ETW logging of method entry, method exit, and exceptions -->
    <!-- Project Reference to the ETW attribute and log provider -->
    <ProjectReference Include="..\..\ATAP.Utilities.ETW\ATAP.Utilities.ETW.csproj" />
  </ItemGroup>

</Project>
