
function Get-DatabaseFunctionsFileHashs {
  # ToDo: make sure this is running in a flyway migration direcotry, e.g. "<repo>/databases/BuildSets/flyway/sql"
  $files = Get-ChildItem -File | Where-Object { $_.Name -match '^(R__|V\d+__).*\.sql$' }
  $rows = @()
  foreach ($f in $files) {
    $hash = Get-FileHash -Path $f.FullName -Algorithm SHA256
    $type = ($f.Name.StartsWith('R__')) ? 'R' : 'V'
    $rows += "(@ManifestId, N'$($f.Name)', '$type', N'$($hash.Hash.ToLower())')"
  }
  $values = ($rows -join ",`n  ")
  $script = @"
-- Auto-generated by CI
DECLARE @ManifestId int = (SELECT TOP 1 ManifestId FROM dbo.SchemaManifest ORDER BY CreatedAt DESC);
INSERT dbo.SchemaManifestFile(ManifestId, FileName, FileType, Sha256Hex) VALUES
  $values;
"@
  # To Do: whatever the highest version present in a filename, increment it and use that
  $baseName = 'Record_Functions_FileHashes.sql'
  $version = '00.01.000361_' # ToDo: make this dynamic
  $path = $version + $baseName
  $script | Set-Content -Path $path -Encoding UTF8

}
