<#
.SYNOPSIS
Synthesizes a valid Pester v5 .Tests.ps1 file from a PesterFile model.

.DESCRIPTION
Takes a PesterFile model hashtable (created by New-PesterFileModel) and
renders it to Pester v5 conformant PowerShell source text. Optionally writes the
output to a .Tests.ps1 file on disk.

Rendering honours all structural rules from the Pester Kind:
- All test assertions are inside It blocks.
- Discovery-phase constructs (BeforeDiscovery, block name resolution) are
  rendered at the top of the file or inside the appropriate block.
- Setup blocks run outer-to-inner; teardown runs inner-to-outer.
- File naming mirrors the source file with the configured Extension.
- Tags are rendered on Describe / Context / It keyword lines.

.PARAMETER Model
Required. A PesterFile model hashtable as returned by New-PesterFileModel.

.PARAMETER OutputPath
Directory path where the .Tests.ps1 file should be written. If omitted, the
function returns the generated text without writing anything to disk.

.PARAMETER Force
When writing to disk, overwrite an existing file without prompting.

.OUTPUTS
String - The rendered Pester v5 source text.

.EXAMPLE
$model = New-PesterFileModel -Name 'Get-RepositoryRoot' `
    -Describes @(New-PesterDescribeBlock -Name 'Get-RepositoryRoot' `
        -Its @(New-PesterItBlock -Name 'Get-RepositoryRoot_ValidGitRepo_ReturnsString' `
               -Body '$result = Get-RepositoryRoot; $result | Should -Not -BeNullOrEmpty'))
$text = New-PesterTestFile -Model $model
$text | Write-Output

.EXAMPLE
New-PesterTestFile -Model $model -OutputPath 'tests/Unit' -Force

Writes the rendered content to 'tests/Unit/Get-RepositoryRoot.Tests.ps1'.

.NOTES
Philote ID: "e5f6a7b8-c9d0-1234-ef56-789012345678"
AI assisted using Powershell.instructions.md as guidelines
#>
function New-PesterTestFile {
  [CmdletBinding(SupportsShouldProcess)]
  [OutputType([string])]
  param(
    [Parameter(Mandatory = $true)]
    [ValidateNotNull()]
    [hashtable]$Model,

    [Parameter(Mandatory = $false)]
    [string]$OutputPath,

    [Parameter(Mandatory = $false)]
    [switch]$Force
  )

  begin {
    $fn = 'New-PesterTestFile'
    $mn = 'ATAP.Utilities.BuildTooling.PowerShell'
    Write-PSFMessage -FunctionName $fn -ModuleName $mn -Level Debug -Message 'Entering New-PesterTestFile'
    # Load required helper functions
    try {
      if (-not (Get-Command -Name 'Get-RepositoryRoot' -CommandType Function -ErrorAction SilentlyContinue)) {
        . 'C:\Dropbox\whertzing\GitHub\ATAP.Utilities\src\ATAP.Utilities.BuildTooling.PowerShell\public\Get-RepositoryRoot.ps1'
      }
      $repositoryRoot = Get-RepositoryRoot

      if (-not (Get-Command -Name 'Get-PVal' -CommandType Function -ErrorAction SilentlyContinue)) {
        . (Join-Path $repositoryRoot 'src\ATAP.Utilities.Powershell\public\Get-ParameterValueFromNeoConfigurationRoot.ps1')
      }
    }
    catch {
      $errorMessage = "Failed to load required functions. Exception: $($_.Exception.Message)"
      Write-PSFMessage -FunctionName $fn -ModuleName $mn -Level Error -Message $errorMessage
      throw
    }
    # Snippet: Check and populate simple parameter as Type
    $Model = Get-PVal -ParameterName 'Model' -originalPSBoundParameters $PSBoundParameters -dottedPath 'Model' -DefaultValue $Model -AsType ([hashtable])
    # Snippet: Check and populate simple parameter
    $OutputPath = Get-PVal -ParameterName 'OutputPath' -originalPSBoundParameters $PSBoundParameters -dottedPath 'OutputPath' -DefaultValue $OutputPath
    # Snippet: Check and populate simple parameter as Type
    $Force = Get-PVal -ParameterName 'Force' -originalPSBoundParameters $PSBoundParameters -dottedPath 'Force' -DefaultValue $Force -AsType ([switch])

    # Validate required model keys
    foreach ($key in @('Name', 'Describes')) {
      if (-not $Model.ContainsKey($key) -or $null -eq $Model[$key]) {
        throw "PesterFile model is missing required key: '$key'."
      }
    }
    if ($Model['Describes'].Count -eq 0) {
      throw 'PesterFile model must contain at least one Describe block.'
    }
  }

  process {
    try {
      $sb = [System.Text.StringBuilder]::new()

      # ── File header comment ───────────────────────────────────────────────────
      $null = $sb.AppendLine("#")
      $null = $sb.AppendLine("# Pester tests for $($Model['Name'])")
      $null = $sb.AppendLine("# Generated by New-PesterTestFile (ATAP.Utilities.BuildTooling.PowerShell)")
      $null = $sb.AppendLine("#")
      $null = $sb.AppendLine("")

      # ── Param block (Discovery phase) ─────────────────────────────────────────
      if (-not [string]::IsNullOrWhiteSpace($Model['ParamBlock'])) {
        $null = $sb.AppendLine($Model['ParamBlock'])
        $null = $sb.AppendLine("")
      }

      # ── BeforeDiscovery (Discovery phase) ─────────────────────────────────────
      if (-not [string]::IsNullOrWhiteSpace($Model['BeforeDiscovery'])) {
        $null = $sb.AppendLine("BeforeDiscovery {")
        foreach ($line in $Model['BeforeDiscovery'] -split "`n") {
          $null = $sb.AppendLine("  $($line.TrimEnd())")
        }
        $null = $sb.AppendLine("}")
        $null = $sb.AppendLine("")
      }

      # ── Describe blocks ───────────────────────────────────────────────────────
      foreach ($describe in $Model['Describes']) {
        $null = $sb.Append($(_Render-PesterDescribeBlock -Block $describe -IndentLevel 0))
      }

      $text = $sb.ToString().TrimEnd()
      Write-PSFMessage -FunctionName $fn -ModuleName $mn -Level Debug -Message "Synthesis complete. Output is $($text.Length) characters."

      # ── Optional file write ───────────────────────────────────────────────────
      if (-not [string]::IsNullOrWhiteSpace($OutputPath)) {
        $extension = if ([string]::IsNullOrWhiteSpace($Model['Extension'])) { '.Tests.ps1' } else { $Model['Extension'] }
        $fileName = "$($Model['Name'])$extension"
        $fullPath = Join-Path $OutputPath $fileName

        if ((Test-Path $fullPath) -and -not $Force) {
          throw "File already exists: '$fullPath'. Use -Force to overwrite."
        }

        if ($PSCmdlet.ShouldProcess($fullPath, 'Write Pester test file')) {
          $null = New-Item -ItemType Directory -Path $OutputPath -Force
          Set-Content -Path $fullPath -Value $text -Encoding UTF8
          Write-PSFMessage -FunctionName $fn -ModuleName $mn -Level Important -Message "Written: $fullPath"
        }
      }

      return $text
    }
    catch {
      $errorMessage = "Failed to synthesize Pester test file '$($Model['Name'])'. Exception: $($_.Exception.Message)"
      Write-PSFMessage -FunctionName $fn -ModuleName $mn -Level Error -Message $errorMessage
      throw
    }
  }

  end {}
}

# ── Internal rendering helpers (private to this file) ────────────────────────

function _Render-PesterDescribeBlock {
  param([hashtable]$Block, [int]$IndentLevel)
  $pad = '  ' * $IndentLevel
  $sb = [System.Text.StringBuilder]::new()

  # Describe keyword line
  $tagStr = _Render-PesterTagParam -Tags $Block['Tags']
  $null = $sb.AppendLine("${pad}Describe '$($Block['Name'])'$tagStr {")

  # Setup/teardown + child blocks
  $innerPad = '  ' * ($IndentLevel + 1)
  $null = $sb.Append($(_Render-PesterSetupTeardown -Block $Block -IndentLevel ($IndentLevel + 1)))

  foreach ($ctx in $Block['Contexts']) {
    $null = $sb.Append($(_Render-PesterContextBlock -Block $ctx -IndentLevel ($IndentLevel + 1)))
  }
  foreach ($it in $Block['Its']) {
    $null = $sb.Append($(_Render-PesterItBlock -Block $it -IndentLevel ($IndentLevel + 1)))
  }

  $null = $sb.AppendLine("${pad}}")
  $null = $sb.AppendLine("")
  return $sb.ToString()
}

function _Render-PesterContextBlock {
  param([hashtable]$Block, [int]$IndentLevel)
  $pad = '  ' * $IndentLevel
  $sb = [System.Text.StringBuilder]::new()

  $tagStr = _Render-PesterTagParam -Tags $Block['Tags']
  $forEachStr = if (-not [string]::IsNullOrWhiteSpace($Block['ForEach'])) { " -ForEach $($Block['ForEach'])" } else { '' }
  $null = $sb.AppendLine("${pad}Context '$($Block['Name'])'$tagStr$forEachStr {")

  $null = $sb.Append($(_Render-PesterSetupTeardown -Block $Block -IndentLevel ($IndentLevel + 1)))

  foreach ($it in $Block['Its']) {
    $null = $sb.Append($(_Render-PesterItBlock -Block $it -IndentLevel ($IndentLevel + 1)))
  }

  $null = $sb.AppendLine("${pad}}")
  $null = $sb.AppendLine("")
  return $sb.ToString()
}

function _Render-PesterItBlock {
  param([hashtable]$Block, [int]$IndentLevel)
  $pad = '  ' * $IndentLevel
  $sb = [System.Text.StringBuilder]::new()

  $tagStr = _Render-PesterTagParam -Tags $Block['Tags']

  # Prefer ForEach over TestCases for Pester v5 style
  $dataStr = ''
  if (-not [string]::IsNullOrWhiteSpace($Block['ForEach'])) {
    $dataStr = " -ForEach $($Block['ForEach'])"
  }
  elseif (-not [string]::IsNullOrWhiteSpace($Block['TestCases'])) {
    $dataStr = " -TestCases $($Block['TestCases'])"
  }

  $null = $sb.AppendLine("${pad}It '$($Block['Name'])'$tagStr$dataStr {")

  $innerPad = '  ' * ($IndentLevel + 1)
  foreach ($line in $Block['Body'] -split "`n") {
    $trimmed = $line.TrimEnd()
    if ($trimmed.Length -gt 0) {
      $null = $sb.AppendLine("${innerPad}${trimmed}")
    }
  }

  $null = $sb.AppendLine("${pad}}")
  return $sb.ToString()
}

function _Render-PesterSetupTeardown {
  param([hashtable]$Block, [int]$IndentLevel)
  $pad = '  ' * $IndentLevel
  $sb = [System.Text.StringBuilder]::new()

  foreach ($blockName in @('BeforeAll', 'BeforeEach', 'AfterEach', 'AfterAll')) {
    if (-not [string]::IsNullOrWhiteSpace($Block[$blockName])) {
      $null = $sb.AppendLine("${pad}${blockName} {")
      $innerPad = '  ' * ($IndentLevel + 1)
      foreach ($line in $Block[$blockName] -split "`n") {
        $trimmed = $line.TrimEnd()
        if ($trimmed.Length -gt 0) {
          $null = $sb.AppendLine("${innerPad}${trimmed}")
        }
      }
      $null = $sb.AppendLine("${pad}}")
    }
  }

  return $sb.ToString()
}

function _Render-PesterTagParam {
  param([string[]]$Tags)
  if ($Tags -and $Tags.Count -gt 0) {
    $tagList = ($Tags | ForEach-Object { "'$_'" }) -join ', '
    return " -Tag $tagList"
  }
  return ''
}
