//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATAP.Console.Console02.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConsoleExceptionResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConsoleExceptionResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ATAP.Console.Console02.Properties.ConsoleExceptionResources", typeof(ConsoleExceptionResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Environment &quot;Production&quot; should not be reached here.
        /// </summary>
        internal static string InvalidCircularEnvironment {
            get {
                return ResourceManager.GetString("InvalidCircularEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The GenericHostLifeTimeString does not match any member of the SupportedGenericHostLifetimes enumeration.{0}.
        /// </summary>
        internal static string InvalidGenericHostLifetimeString {
            get {
                return ResourceManager.GetString("InvalidGenericHostLifetimeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The KindOfHostBuilderToBuildString {0} specified in the GenericHostConfigurationRoot does not match any member of the KindOfHostBuilderToBuild enumeration..
        /// </summary>
        internal static string InvalidKindOfHostBuilderToBuildString {
            get {
                return ResourceManager.GetString("InvalidKindOfHostBuilderToBuildString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The initial Environment from the initialConfigurationRoot is {0}, and after reconfiguration, the Environment is {1}. this is a mis-match, and indicates a problem with the environment-specific configuration providers. Environment-specific configuration providers are not allowed to change the environment..
        /// </summary>
        internal static string InvalidRedeclarationOfEnvironment {
            get {
                return ResourceManager.GetString("InvalidRedeclarationOfEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Environment enumeration argument specified {0} is not supported..
        /// </summary>
        internal static string InvalidSupportedEnvironment {
            get {
                return ResourceManager.GetString("InvalidSupportedEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The WebHostBuilder string {0} specified in the GenericHostConfigurationRoot does not match any member of the SupportedWebHostBuilders enumeration..
        /// </summary>
        internal static string InvalidWebHostBuilderToBuildString {
            get {
                return ResourceManager.GetString("InvalidWebHostBuilderToBuildString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The genericHostLifetime enumeration value specified  is not supported. {0}.
        /// </summary>
        internal static string UnsupportedGenericHostLifetime {
            get {
                return ResourceManager.GetString("UnsupportedGenericHostLifetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The WebHostBuilder enumeration argument specified {0} is not supported..
        /// </summary>
        internal static string UnsupportedWebHostBuilderToBuild {
            get {
                return ResourceManager.GetString("UnsupportedWebHostBuilderToBuild", resourceCulture);
            }
        }
    }
}
