USE [master]
GO

-- Create the database, with the standard SQL Server defaults as of 12/2020
CREATE DATABASE [GenerateProgramDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GenerateProgramDB', FILENAME = N'C:\LocalDBs\Data\GenerateProgramDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'GenerateProgramDB_log', FILENAME = N'C:\LocalDBs\Logs\GenerateProgramDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GenerateProgramDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [GenerateProgramDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [GenerateProgramDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [GenerateProgramDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [GenerateProgramDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [GenerateProgramDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [GenerateProgramDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [GenerateProgramDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [GenerateProgramDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [GenerateProgramDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [GenerateProgramDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [GenerateProgramDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [GenerateProgramDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [GenerateProgramDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [GenerateProgramDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [GenerateProgramDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [GenerateProgramDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [GenerateProgramDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [GenerateProgramDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [GenerateProgramDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [GenerateProgramDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [GenerateProgramDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [GenerateProgramDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [GenerateProgramDB] SET RECOVERY FULL 
GO

ALTER DATABASE [GenerateProgramDB] SET  MULTI_USER 
GO

ALTER DATABASE [GenerateProgramDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [GenerateProgramDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [GenerateProgramDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [GenerateProgramDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [GenerateProgramDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [GenerateProgramDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [GenerateProgramDB] SET  READ_WRITE 
GO


