---
# code: language=ansible
- name: win_shell GetDate
  hosts: all
  tasks:
    - name: check getdate
      ansible.windows.win_shell: |
        Get-Date
      register: command_output
    - name: command output
      ansible.builtin.debug:
        var: command_output.stdout_lines
