USE [ATAP.Utilities]
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE dbo.GComment(
	Id int IDENTITY(1,1) NOT NULL,
  , CONSTRAINT PK_GComment PRIMARY KEY NONCLUSTERED (Id)
) ON [PRIMARY]
GO
