USE [ATAPUtilities]
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE dbo.RuleSet(
Id int IDENTITY(1,1) NOT NULL CONSTRAINT PK_RuleSet PRIMARY KEY NONCLUSTERED (Id)
, GName nvarchar(512) NOT NULL
, Validity datetime NOT NULL
)	ON [PRIMARY]
GO
