USE [ATAPUtilities]
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE dbo.Map_RuleSet_Rule(
	Id int IDENTITY(1,1) NOT NULL CONSTRAINT PK_Map_RuleSet_Rule PRIMARY KEY NONCLUSTERED
	, FK_RuleSet int NOT NULL CONSTRAINT FK_RuleSet FOREIGN KEY (FK_RuleSet) REFERENCES dbo.RuleSet (Id)
	, FK_Rule int NOT NULL CONSTRAINT FK_Rule  FOREIGN KEY (FK_Rule) REFERENCES dbo.[Rule] (Id)
	, SortOrder int NOT NULL CONSTRAINT DF_Map_RuleSet_Rule_SortOrder  DEFAULT 1
) ON [PRIMARY]
GO


