<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <IsPackable>true</IsPackable>
    <MajorVersion>0</MajorVersion>
    <MinorVersion>1</MinorVersion>
    <PatchVersion>0</PatchVersion>
    <PackageLifeCycleStage>Development</PackageLifeCycleStage>
    <PackageLabel>Alpha</PackageLabel>
    <EnableDefaultItems>false</EnableDefaultItems>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="Interfaces\ATAP.Utilities.Loader.Interfaces.csproj" />
    <ProjectReference Include="Model\ATAP.Utilities.Loader.Model.csproj" />
    <ProjectReference Include="StringConstants\ATAP.Utilities.Loader.StringConstants.csproj" />
  </ItemGroup>

</Project>
