<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <EnableDefaultItems>false</EnableDefaultItems>
    <OutputType>Library</OutputType>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <IsPackable>true</IsPackable>
    <Description>Aggregator package for ATAP.Utilities.Configuration libraries.</Description>
  </PropertyGroup>

  <!-- Aggregate all Configuration child projects -->
  <ItemGroup>
    <ProjectReference Include="Extensions\ATAP.Utilities.Configuration.Extensions.csproj" PrivateAssets="all"/>
    <ProjectReference Include="Secrets\ATAP.Utilities.Configuration.Secrets.csproj" PrivateAssets="all" />
    <ProjectReference Include="Secrets\Shims\Bitwarden\ATAP.Utilities.Configuration.Secrets.Shim.Bitwarden.csproj" PrivateAssets="all" />
    <ProjectReference Include="..\ATAP.Utilities.Secrets\ATAP.Utilities.Secrets.csproj" />
  </ItemGroup>

</Project>
