<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <IsPackable>true</IsPackable>
    <EnableDefaultItems>false</EnableDefaultItems>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="Newtonsoft\ATAP.Utilities.Serializer.Shim.Newtonsoft.csproj" PrivateAssets="all" />
    <ProjectReference Include="Plugin\ATAP.Utilities.Serializer.Shim.Plugin.csproj" PrivateAssets="all" />
    <ProjectReference Include="ServiceStack\ATAP.Utilities.Serializer.Shim.ServiceStack.csproj" PrivateAssets="all" />
    <ProjectReference Include="SystemTextJson\ATAP.Utilities.Serializer.Shim.SystemTextJson.csproj" PrivateAssets="all"/>
  </ItemGroup>
</Project>
