<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <IsPackable>true</IsPackable>
  </PropertyGroup>


  <!-- Reactive Extensions -->
  <ItemGroup>
    <PackageReference Include="System.Reactive" />
  </ItemGroup>

  <!-- Packages and projects to implement IL Weaving using Fody during the build process -->
  <ItemGroup>
    <!-- Packages to implement ETW logging of method entry, method exit, and exceptions -->
    <!-- Project Reference to the ETW attribute and log provider -->
    <ProjectReference Include="..\ATAP.Utilities.ETW\ATAP.Utilities.ETW.csproj" />
  </ItemGroup>

</Project>
