---
all:
  
windows:
  hosts:
    ncat016:
    utat022:
    utat01:
    ncat-ltb1:
    ncat040:

  webservers:
    hosts:
    ncat016:
    utat022:
    utat01:
    ncat-ltb1:
    ncat040:

  dbservers:
    hosts:
    ncat016:
    utat022:
    utat01:
    ncat-ltb1:
    ncat040:

  production:
    hosts:
      ncat016:

  development:
    hosts:
      utat01:
      utat022:

  qualityassurance:
    hosts:
    ncat-ltb1:
    ncat040:

  vars:
    ansible_remote_tmp: D:\Temp\Ansible
    ansible_shell_type: pwsh
    become_method: runas
