-- Calls mirroring your original tests, now by RuleSet
SELECT * FROM dbo.SORTED_RULEITEMID_RULESETID_Is_VALUE(0,-1,0,0);
SELECT * FROM dbo.SORTED_RULEITEMID_RULESETID_Is_VALUE(0,-1,1,0);
SELECT * FROM dbo.SORTED_RULEITEMID_RULESETID_Is_VALUE(0,-1,2,0);
SELECT * FROM dbo.SORTED_RULEITEMID_RULESETID_Is_VALUE(0,-1,4,0);
SELECT * FROM dbo.SORTED_RULEITEMID_RULESETID_Is_VALUE(0,-1,5,0);
SELECT * FROM dbo.SORTED_RULEITEMID_RULESETID_Is_VALUE(0,-1,6,0);
SELECT * FROM dbo.SORTED_RULEITEMID_RULESETID_Is_VALUE(0,-1,7,0);
SELECT * FROM dbo.SORTED_RULEITEMID_RULESETID_Is_VALUE(0,-1,8,0);
SELECT * FROM dbo.SORTED_RULEITEMID_RULESETID_Is_VALUE(0,-1,9,0);

SELECT COUNT(*) AS RuleSetCount FROM dbo.RuleSet;                 -- expect 11
SELECT COUNT(*) AS ItemsInRuleSet8 FROM dbo.RuleSetHavingRuleItem -- expect 30
 WHERE RuleSetID = 8;
