<Project Sdk="Microsoft.NET.Sdk">

 <PropertyGroup>
    <OutputType>Library</OutputType>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <!-- The ServiceStack JSON Library to use -->
  <ItemGroup>
    <PackageReference Include="ServiceStack.Text" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Interfaces\ATAP.Utilities.Serializer.Interfaces.csproj" />
    <ProjectReference Include="..\..\..\ATAP.Utilities.Collection.Extensions\ATAP.Utilities.Collection.Extensions.csproj" />
  </ItemGroup>

</Project>
