namespace ATAP.Utilities.ManimVideoGenerator
{
  /// <summary>
  /// The outcome produced by a single agent execution.
  /// </summary>
  public interface IAgentResult
  {
    /// <summary>Whether the agent approved or rejected its input.</summary>
    ValidationStatusEnum Status { get; }

    /// <summary>The text output generated by the agent (description, code, or verdict).</summary>
    string Output { get; }

    /// <summary>Optional rejection reason; null when <see cref="Status"/> is Approved.</summary>
    string? RejectionReason { get; }
  }
}
