<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <IsPackable>true</IsPackable>
    <!-- Facade project - disable default items to prevent including child project source files -->
    <EnableDefaultItems>false</EnableDefaultItems>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="DefaultConfiguration\ATAP.Utilities.Philote.DefaultConfiguration.csproj" PrivateAssets="all" />
    <ProjectReference Include="Interfaces\ATAP.Utilities.Philote.Interfaces.csproj" PrivateAssets="all" />
    <ProjectReference Include="Models\ATAP.Utilities.Philote.Models.csproj" PrivateAssets="all" />
    <ProjectReference Include="JsonConverter.Shim.SystemTextJson\ATAP.Utilities.Philote.JsonConverter.Shim.SystemTextJson.csproj" PrivateAssets="all" />
  </ItemGroup>

</Project>
