-- V00.02.000050 — V4-E15 harmless smoke migration.
-- Intentionally performs no schema or data changes; it exists only to prove the
-- database change-package BuildMaster pipeline can carry a Flyway migration artifact.
--
-- Numbered in the canonical dotted, zero-padded Flyway scheme shared with the
-- consolidated authoritative set in Database/Flyway/SQL (Sprint 0009 Task 9.12:
-- the packaged change unit and the consolidated set now use ONE scheme,
-- V00.0X.NNNNNN). This version is strictly greater than the consolidated baseline
-- top (00.02.000040, Add AgentText Rule Kind), so it sorts cleanly when applied on
-- top of a tier already carrying that baseline.
PRINT 'V00.02.000050 V4-E15 harmless smoke migration executed.';
