<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <IsPackable>true</IsPackable>
    <!-- Assembly, File, and Package Information for this assembly-->
    <!-- Build and revision are created based on date-->
    <MajorVersion>0</MajorVersion>
    <MinorVersion>1</MinorVersion>
    <PatchVersion>0</PatchVersion>
    <!-- Current Lifecycle stage for this assembly-->
    <PackageLifeCycleStage>Development</PackageLifeCycleStage>
    <!-- NuGet Package Label for the Nuget Package if the LifeCyclestage is not Production-->
    <!-- However, if the LifeCyclestage is Production, the NuGet Package Label is ignored, but MSBuild expects a non-null value  -->
    <PackageLabel>Alpha</PackageLabel>
    <!-- Facade/Aggregator project - no source files to compile -->
    <EnableDefaultItems>false</EnableDefaultItems>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="Configuration\ATAP.Utilities.ComputerInventory.Configuration.csproj" />
    <ProjectReference Include="Enumerations\ATAP.Utilities.ComputerInventory.Enumerations.csproj" />
    <ProjectReference Include="Extensions\ATAP.Utilities.ComputerInventory.Extensions.csproj" />
    <ProjectReference Include="Hardware\ATAP.Utilities.ComputerInventory.Hardware.csproj" />
    <ProjectReference Include="Interfaces\ATAP.Utilities.ComputerInventory.Interfaces.csproj" />
    <ProjectReference Include="Models\ATAP.Utilities.ComputerInventory.Models.csproj" />
    <ProjectReference Include="ProcessInfo\ATAP.Utilities.ComputerInventory.ProcessInfo.csproj" />
    <ProjectReference Include="Software\ATAP.Utilities.ComputerInventory.Software.csproj" />
  </ItemGroup>

</Project>
