#
# Module manifest for module 'ATAP.Utilities.Powershell.GELFLogging'
#
# Generated by: Bill Hertzing for ATAPUtilities.org
#
# Generated on: 8/2/2026
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'ATAP.Utilities.Powershell.GELFLogging.psm1'

# Version number of this module.
ModuleVersion = '0.1.1'

# Supported PSEditions
CompatiblePSEditions = 'Core'

# ID used to uniquely identify this module
GUID = '911a92ae-f079-4e42-ad72-76962fc02b95'

# Author of this module
Author = 'Bill Hertzing for ATAPUtilities.org'

# Company or vendor of this module
CompanyName = 'ATAPUtilities.org'

# Copyright statement for this module
Copyright = '(c) Bill Hertzing for ATAPUtilities.org. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Explicit enable/disable/query control of PSFramework logging to a SEQ GELF (UDP) ingestor. Child module of ATAP.Utilities.PowerShell (Task 14.62).'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '7.0'

# Modules that must be imported into the global environment prior to importing this module
# PSFramework supplies Register-PSFLoggingProvider / Set-PSFLoggingProvider / Write-PSFMessage.
# PSGELF is deliberately NOT a RequiredModule: it is the UDP transport, needed only by
# Enable-SeqGelfLogging, and is imported on demand by the private Assert-PSGelfAvailable.
# Making it required would force every host that merely wants to DISABLE or QUERY the sink
# to install the transport first. It is declared in PSData.ExternalModuleDependencies instead.
RequiredModules = @(@{ModuleName = 'PSFramework'; ModuleVersion = '1.12.346'; })

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @(
    'Disable-SeqGelfLogging',
    'Enable-SeqGelfLogging',
    'Get-SeqGelfLoggingStatus'
)

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('ATAP', 'Logging', 'PSFramework', 'GELF', 'SEQ', 'Telemetry')

        # ReleaseNotes of this module
        ReleaseNotes = 'See ReleaseNotes.md. 0.1.1 - initial extraction from ATAP.Utilities.PowerShell with an explicit Disable and a read-only status query (Task 14.62).'

        # External dependent modules of this module
        ExternalModuleDependencies = @('PSGELF')

    } # End of PSData hashtable

} # End of PrivateData hashtable

}
