<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <IsPackable>true</IsPackable>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\ATAP.Utilities.DateTime.Model\ATAP.Utilities.DateTime.Model.csproj" />
    <ProjectReference Include="..\..\ATAP.Utilities.DateTime.StringConstants\ATAP.Utilities.DateTime.StringConstants.csproj" />
    <ProjectReference Include="..\Interfaces\ATAP.Utilities.Philote.Interfaces.csproj" />
    <ProjectReference Include="..\Models\ATAP.Utilities.Philote.Models.csproj" />
    <ProjectReference Include="..\..\ATAP.Utilities.Serializer\Interfaces\ATAP.Utilities.Serializer.Interfaces.csproj" />
    <ProjectReference Include="..\..\ATAP.Utilities.StronglyTypedId\Interfaces\ATAP.Utilities.StronglyTypedId.Interfaces.csproj" />
    <ProjectReference Include="..\..\ATAP.Utilities.StronglyTypedId\Models\ATAP.Utilities.StronglyTypedId.Models.csproj" />
  </ItemGroup>


</Project>
