<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Interfaces\ATAP.Utilities.Serializer.Interfaces.csproj" />
    <ProjectReference Include="..\..\Model\ATAP.Utilities.Serializer.Model.csproj" />
    <ProjectReference Include="..\..\..\ATAP.Utilities.Collection.Extensions\ATAP.Utilities.Collection.Extensions.csproj" />
  </ItemGroup>

  <!-- Loader interfaces and classes for any Assembly that may be loaded by the dynamic Loader, only works for TargetFramework NetCore -->
  <ItemGroup Condition="$(TargetFramework.Contains('netcore'))">
    <ProjectReference Include="..\..\..\ATAP.Utilities.Loader\ATAP.Utilities.Loader.csproj" />
  </ItemGroup>

</Project>
