#
# Module manifest for module 'ATAP.Utilities.RulesManagement.PowerShell'
#
# Generated by: Bill Hertzing for ATAPUtilities.org
#
# Generated on: 6/13/2026
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule           = 'ATAP.Utilities.RulesManagement.PowerShell.psm1'

    # Version number of this module.
    ModuleVersion        = '0.1.4'

    # Supported PSEditions
    CompatiblePSEditions = 'Desktop', 'Core'

    # ID used to uniquely identify this module
    GUID                 = '8959f7fd-c0fd-45c1-bd69-e6f8a73f7202'

    # Author of this module
    Author               = 'Bill Hertzing for ATAPUtilities.org'

    # Company or vendor of this module
    CompanyName          = 'ATAPUtilities.org'

    # Copyright statement for this module
    Copyright            = '(c) 2018 - 2026  Bill Hertzing . All rights reserved. All code is under the MIT license'

    # Description of the functionality provided by this module
    Description          = 'PowerShell cmdlets for the ATAP.Utilities RRSBS rule-grammar system: read and validate Rule Kinds and grammar from the ATAPUtilities database, author new Rule Kind Flyway migrations, and round-trip AgentText agent/instruction records between the canonical .ai source tree, the rules tables, and the rendered tool-native adapter files.'

    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion    = '5.1'

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport    = 'Add-RuleKindToCompendium', 'Export-AgentTextToFiles',
    'Get-AgentTextFromDatabase', 'Get-GrammarForKind', 'Get-RuleKinds',
    'Get-RulePrimitiveInputs', 'Import-AgentTextFromFiles', 'New-RuleKindMigration',
    'Save-AgentTextToDatabase', 'Sync-RuleDocumentation', 'Test-CompositionOrder',
    'Test-FlywayMigrationDryRun'

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport      = '*'

    # Variables to export from this module
    VariablesToExport    = '*'

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport      = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData          = @{

        PSData = @{

            # Prerelease string cleared for the 0.1.4 stable release (Task 9.5,
            # Gate 7 "stable version finalization"). Re-add a Prerelease label only
            # for a future prerelease build, never for a Production promotion.

        } # End of PSData hashtable

    } # End of PrivateData hashtable

}
