<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <!-- Extensions methods on File and Directory types, along with a Globbing library -->
  <ItemGroup>
    <ProjectReference Include="..\..\ATAP.Utilities.FIleIO\ATAP.Utilities.FileIO.csproj" />
  </ItemGroup>

</Project>
