# ToDo comment  based help
$global:configRootKeys = @{

  'IsElevatedConfigRootKey' = 'IsElevated'
  'CloudBasePathConfigRootKey' = 'CloudBasePath'
  'DropboxBasePathConfigRootKey' = 'DropboxBasePath'
  'OneDriveBasePathConfigRootKey' = 'OneDriveBasePath'
  'FastTempBasePathConfigRootKey' = 'FastTempBasePath'
  'BigTempBasePathConfigRootKey' = 'BigTempBasePath'
  'GitExePathConfigRootKey' = 'GitExePath'
  'JavaExePathConfigRootKey' = 'JavaExePath'
  'JenkinsNodeRolesConfigRootKey' = 'JenkinsNodeRoles'
  'ChocolateyBinDirConfigRootKey' = 'ChocolateyBinDir'
  'ChocolateyLibDirConfigRootKey' = 'ChocolateyLibDir'
  'PackageDropPathsConfigRootKey' = 'PackageDropPaths'
  'WindowsDocumentationBuildConfigRootKey' = 'WindowsDocumentationBuild'
  'BuildImageFromPlantUMLConfigRootKey' = 'BuildImageFromPlantUMPowershellCmdlet'
  'WindowsCodeBuildConfigRootKey' = 'WindowsCodeBuild'
  'WindowsUnitTestConfigRootKey' = 'WindowsUnitTest'
  'MSBuildExePathConfigRootKey' = 'MSBuildExePath'
  'DocFXExePathConfigRootKey' = 'DocFXExePath'
  'DotnetExePathConfigRootKey' = 'DotnetExePath'
  'PlantUMLJarPathConfigRootKey' = 'PlantUMLJarPath'
  'PlantUmlClassDiagramGeneratorExePathConfigRootKey' = 'PlantUmlClassDiagramGeneratorExePath'
  'BuildImageFromPlantUMLPowershellCmdletNameConfigRootKey' = 'BuildImageFromPlantUMLPowershellCmdletName'
  'SQLServerPSModulePathsConfigRootKey' = 'SQLServerPSModulePaths'
  'SQLServerConnectionStringConfigRootKey' = 'SQLServerConnectionString'
}
