###################################################
## Databases keys. segment of global_ConfigRootKeys.ps1
$global:configRootKeys.Add('DatabasesCollectionConfigRootKey', 'DatabasesCollection')
$global:configRootKeys.Add('DatabaseBuildSetsNameConfigRootKey', 'BuildSets')
$global:configRootKeys.Add('DatabasePCMSCNameConfigRootKey', 'PCMSC')
$global:configRootKeys.Add('DatabaseGmailNameConfigRootKey', 'Gmail')
$global:configRootKeys.Add('ProvisionForFlywayConfigRootKey', 'ProvisionForFlyway')

$global:configRootKeys.Add('DatabaseHostConfigRootKey', 'DatabaseHost')
$global:configRootKeys.Add('ConnectionMethodConfigRootKey', 'ConnectionMethod') # for Get-PVal to work this must match the parameter name exactly
$global:configRootKeys.Add('SqlInstanceConfigRootKey', 'SqlInstance')
$global:configRootKeys.Add('DatabasePathConfigRootKey', 'DatabasePath')
$global:configRootKeys.Add('ScriptDirectoryConfigRootKey', 'ScriptDirectory')
$global:configRootKeys.Add('UseNamedLoginConfigRootKey', 'UseNamedLogin')
$global:configRootKeys.Add('LoginNameConfigRootKey', 'LoginName')
$global:configRootKeys.Add('LoginPasswordVaultKeyConfigRootKey', 'LoginPasswordVaultKey')

$global:configRootKeys.Add('DatabaseBuildSetsProductionDatabaseHostConfigRootKey', 'DatabaseBuildSetsProductionDatabaseHost')
$global:configRootKeys.Add('DatabaseBuildSetsProductionConnectionMethodConfigRootKey', 'DatabaseBuildSetsProductionConnectionMethod')
$global:configRootKeys.Add('DatabaseBuildSetsProductionSqlInstanceConfigRootKey', 'DatabaseBuildSetsProductionSqlInstance')
$global:configRootKeys.Add('DatabaseBuildSetsProductionDatabasePathConfigRootKey', 'DatabaseBuildSetsProductionDatabasePath')
$global:configRootKeys.Add('DatabaseBuildSetsProductionScriptDirectoryConfigRootKey', 'DatabaseBuildSetsProductionScriptDirectory')
$global:configRootKeys.Add('DatabaseBuildSetsProductionUseNamedLoginConfigRootKey', 'DatabaseBuildSetsProductionUseNamedLogin')
$global:configRootKeys.Add('DatabaseBuildSetsProductionLoginNameConfigRootKey', 'DatabaseBuildSetsProductionLoginName')
$global:configRootKeys.Add('DatabaseBuildSetsProductionLoginPasswordVaultKeyConfigRootKey', 'DatabaseBuildSetsProductionLoginPasswordVaultKey')

$global:configRootKeys.Add('DatabaseBuildSetsTestingDatabaseHostConfigRootKey', 'DatabaseBuildSetsTestingDatabaseHost')
$global:configRootKeys.Add('DatabaseBuildSetsTestingConnectionMethodConfigRootKey', 'DatabaseBuildSetsTestingConnectionMethod')
$global:configRootKeys.Add('DatabaseBuildSetsTestingSqlInstanceConfigRootKey', 'DatabaseBuildSetsTestingSqlInstance')
$global:configRootKeys.Add('DatabaseBuildSetsTestingDatabasePathConfigRootKey', 'DatabaseBuildSetsTestingDatabasePath')
$global:configRootKeys.Add('DatabaseBuildSetsTestingScriptDirectoryConfigRootKey', 'DatabaseBuildSetsTestingScriptDirectory')
$global:configRootKeys.Add('DatabaseBuildSetsTestingUseNamedLoginConfigRootKey', 'DatabaseBuildSetsTestingUseNamedLogin')
$global:configRootKeys.Add('DatabaseBuildSetsTestingLoginNameConfigRootKey', 'DatabaseBuildSetsTestingLoginName')
$global:configRootKeys.Add('DatabaseBuildSetsTestingLoginPasswordVaultKeyConfigRootKey', 'DatabaseBuildSetsTestingLoginPasswordVaultKey')

$global:configRootKeys.Add('DatabaseBuildSetsDevelopmentDatabaseHostConfigRootKey', 'DatabaseBuildSetsDevelopmentDatabaseHost')
$global:configRootKeys.Add('DatabaseBuildSetsDevelopmentConnectionMethodConfigRootKey', 'DatabaseBuildSetsDevelopmentConnectionMethod')
$global:configRootKeys.Add('DatabaseBuildSetsDevelopmentSqlInstanceConfigRootKey', 'DatabaseBuildSetsDevelopmentSqlInstance')
$global:configRootKeys.Add('DatabaseBuildSetsDevelopmentDatabasePathConfigRootKey', 'DatabaseBuildSetsDevelopmentDatabasePath')
$global:configRootKeys.Add('DatabaseBuildSetsDevelopmentScriptDirectoryConfigRootKey', 'DatabaseBuildSetsDevelopmentScriptDirectory')
$global:configRootKeys.Add('DatabaseBuildSetsDevelopmentUseNamedLoginConfigRootKey', 'DatabaseBuildSetsDevelopmentUseNamedLogin')
$global:configRootKeys.Add('DatabaseBuildSetsDevelopmentLoginNameConfigRootKey', 'DatabaseBuildSetsDevelopmentLoginName')
$global:configRootKeys.Add('DatabaseBuildSetsDevelopmentLoginPasswordVaultKeyConfigRootKey', 'DatabaseBuildSetsDevelopmentLoginPasswordVaultKey')

$global:configRootKeys.Add('DatabaseBuildSetsExperimentalDatabaseHostConfigRootKey', 'DatabaseBuildSetsExperimentalDatabaseHost')
$global:configRootKeys.Add('DatabaseBuildSetsExperimentalConnectionMethodConfigRootKey', 'DatabaseBuildSetsExperimentalConnectionMethod')
$global:configRootKeys.Add('DatabaseBuildSetsExperimentalSqlInstanceConfigRootKey', 'DatabaseBuildSetsExperimentalSqlInstance')
$global:configRootKeys.Add('DatabaseBuildSetsExperimentalDatabasePathConfigRootKey', 'DatabaseBuildSetsExperimentalDatabasePath')
$global:configRootKeys.Add('DatabaseBuildSetsExperimentalScriptDirectoryConfigRootKey', 'DatabaseBuildSetsExperimentalScriptDirectory')
$global:configRootKeys.Add('DatabaseBuildSetsExperimentalUseNamedLoginConfigRootKey', 'DatabaseBuildSetsExperimentalUseNamedLogin')
$global:configRootKeys.Add('DatabaseBuildSetsExperimentalLoginNameConfigRootKey', 'DatabaseBuildSetsExperimentalLoginName')
$global:configRootKeys.Add('DatabaseBuildSetsExperimentalLoginPasswordVaultKeyConfigRootKey', 'DatabaseBuildSetsExperimentalLoginPasswordVaultKey')

$global:configRootKeys.Add('DatabasePCMSCExperimentalDatabaseHostConfigRootKey', 'DatabasePCMSCExperimentalDatabaseHost')
$global:configRootKeys.Add('DatabasePCMSCExperimentalConnectionMethodConfigRootKey', 'DatabasePCMSCExperimentalConnectionMethod')
$global:configRootKeys.Add('DatabasePCMSCExperimentalSqlInstanceConfigRootKey', 'DatabasePCMSCExperimentalSqlInstance')
$global:configRootKeys.Add('DatabasePCMSCExperimentalDatabasePathConfigRootKey', 'DatabasePCMSCExperimentalDatabasePath')
$global:configRootKeys.Add('DatabasePCMSCExperimentalScriptDirectoryConfigRootKey', 'DatabasePCMSCExperimentalScriptDirectory')
$global:configRootKeys.Add('DatabasePCMSCExperimentalUseNamedLoginConfigRootKey', 'DatabasePCMSCExperimentalUseNamedLogin')
$global:configRootKeys.Add('DatabasePCMSCExperimentalLoginNameConfigRootKey', 'DatabasePCMSCExperimentalLoginName')
$global:configRootKeys.Add('DatabasePCMSCExperimentalLoginPasswordVaultKeyConfigRootKey', 'DatabasePCMSCExperimentalLoginPasswordVaultKey')

$global:configRootKeys.Add('DatabasePCMSCDevelopmentDatabaseHostConfigRootKey', 'DatabasePCMSCDevelopmentDatabaseHost')
$global:configRootKeys.Add('DatabasePCMSCDevelopmentConnectionMethodConfigRootKey', 'DatabasePCMSCDevelopmentConnectionMethod')
$global:configRootKeys.Add('DatabasePCMSCDevelopmentSqlInstanceConfigRootKey', 'DatabasePCMSCDevelopmentSqlInstance')
$global:configRootKeys.Add('DatabasePCMSCDevelopmentDatabasePathConfigRootKey', 'DatabasePCMSCDevelopmentDatabasePath')
$global:configRootKeys.Add('DatabasePCMSCDevelopmentScriptDirectoryConfigRootKey', 'DatabasePCMSCDevelopmentScriptDirectory')
$global:configRootKeys.Add('DatabasePCMSCDevelopmentUseNamedLoginConfigRootKey', 'DatabasePCMSCDevelopmentUseNamedLogin')
$global:configRootKeys.Add('DatabasePCMSCDevelopmentLoginNameConfigRootKey', 'DatabasePCMSCDevelopmentLoginName')
$global:configRootKeys.Add('DatabasePCMSCDevelopmentLoginPasswordVaultKeyConfigRootKey', 'DatabasePCMSCDevelopmentLoginPasswordVaultKey')

$global:configRootKeys.Add('DatabaseGmailExperimentalDatabaseHostConfigRootKey', 'DatabaseGmailExperimentalDatabaseHost')
$global:configRootKeys.Add('DatabaseGmailExperimentalConnectionMethodConfigRootKey', 'DatabaseGmailExperimentalConnectionMethod')
$global:configRootKeys.Add('DatabaseGmailExperimentalSqlInstanceConfigRootKey', 'DatabaseGmailExperimentalSqlInstance')
$global:configRootKeys.Add('DatabaseGmailExperimentalDatabasePathConfigRootKey', 'DatabaseGmailExperimentalDatabasePath')
$global:configRootKeys.Add('DatabaseGmailExperimentalScriptDirectoryConfigRootKey', 'DatabaseGmailExperimentalScriptDirectory')
$global:configRootKeys.Add('DatabaseGmailExperimentalUseNamedLoginConfigRootKey', 'DatabaseGmailExperimentalUseNamedLogin')
$global:configRootKeys.Add('DatabaseGmailExperimentalLoginNameConfigRootKey', 'DatabaseGmailExperimentalLoginName')
$global:configRootKeys.Add('DatabaseGmailExperimentalLoginPasswordVaultKeyConfigRootKey', 'DatabaseGmailExperimentalLoginPasswordVaultKey')

$global:configRootKeys.Add('DatabaseGmailDevelopmentDatabaseHostConfigRootKey', 'DatabaseGmailDevelopmentDatabaseHost')
$global:configRootKeys.Add('DatabaseGmailDevelopmentConnectionMethodConfigRootKey', 'DatabaseGmailDevelopmentConnectionMethod')
$global:configRootKeys.Add('DatabaseGmailDevelopmentSqlInstanceConfigRootKey', 'DatabaseGmailDevelopmentSqlInstance')
$global:configRootKeys.Add('DatabaseGmailDevelopmentDatabasePathConfigRootKey', 'DatabaseGmailDevelopmentDatabasePath')
$global:configRootKeys.Add('DatabaseGmailDevelopmentScriptDirectoryConfigRootKey', 'DatabaseGmailDevelopmentScriptDirectory')
$global:configRootKeys.Add('DatabaseGmailDevelopmentUseNamedLoginConfigRootKey', 'DatabaseGmailDevelopmentUseNamedLogin')
$global:configRootKeys.Add('DatabaseGmailDevelopmentLoginNameConfigRootKey', 'DatabaseGmailDevelopmentLoginName')
$global:configRootKeys.Add('DatabaseGmailDevelopmentLoginPasswordVaultKeyConfigRootKey', 'DatabaseGmailDevelopmentLoginPasswordVaultKey')
