<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <IsPackable>true</IsPackable>
    <!-- Assembly, File, and Package Information for this assembly-->
    <!-- Build and revision are created based on date-->
    <MajorVersion>0</MajorVersion>
    <MinorVersion>1</MinorVersion>
    <PatchVersion>0</PatchVersion>
    <!-- Current Lifecycle stage for this assembly-->
    <PackageLifeCycleStage>Development</PackageLifeCycleStage>
    <!-- NuGet Package Label for the Nuget Package if the LifeCyclestage is not Production-->
    <!-- However, if the LifeCyclestage is Production, the NuGet Package Label is ignored, but MSBuild expects a non-null value  -->
    <PackageLabel>Alpha</PackageLabel>
    <!-- Facade/Aggregator project - no source files to compile -->
    <EnableDefaultItems>false</EnableDefaultItems>
  </PropertyGroup>

  <ItemGroup>
    <!-- Project references to all child projects -->
    <ProjectReference Include="Model\ATAP.Utilities.Persistence.csproj" />
    <ProjectReference Include="Extensions\ATAP.Utilities.Persistence.Extensions.csproj" />
    <ProjectReference Include="Interfaces\ATAP.Utilities.Persistence.Interfaces.csproj" />
    <ProjectReference Include="StringConstants\ATAP.Utilities.Persistence.StringConstants.csproj" />
  </ItemGroup>

</Project>
