USE [ATAP.Utilities]
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE dbo.GBody(
	Id int IDENTITY(1,1) NOT NULL CONSTRAINT PK_GBody PRIMARY KEY NONCLUSTERED (Id)
	, FK_GComment int CONSTRAINT FK_GBody_GComment  FOREIGN KEY (FK_GComment) REFERENCES dbo.GComment (Id)
) ON [PRIMARY]
GO
