USE [ATAP.Utilities]
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE dbo.Map_GComment_GStatement(
	Id int IDENTITY(1,1) NOT NULL CONSTRAINT PK_Map_GComment_GStatement  PRIMARY KEY NONCLUSTERED
	, FK_GComment int NOT NULL CONSTRAINT FK_GComment  FOREIGN KEY (FK_GComment) REFERENCES dbo.GComment (Id)
	, FK_GStatement int NOT NULL CONSTRAINT FK_GStatement  FOREIGN KEY (FK_GStatement) REFERENCES dbo.GStatement (Id)
	, SortOrder int NOT NULL CONSTRAINT DF_Map_GComment_GStatement_SortOrder  DEFAULT 1
) ON [PRIMARY]
GO
