using System;
using System.Collections.Generic;

using ATAP.Utilities.StronglyTypedId;

namespace ATAP.Utilities.GenerateProgram {

  public record GProjectUnitId<TValue> : AbstractStronglyTypedId<TValue>, IGProjectUnitId<TValue> where TValue : notnull {}
  public class GProjectUnit<TValue> : IGProjectUnit<TValue> where TValue : notnull {
    public GProjectUnit(string gName = default, string gRelativePath = default, string gFileSuffix = default,
    Dictionary<IGPropertyGroupInProjectUnitId<TValue>, IGPropertyGroupInProjectUnit<TValue>> gPropertyGroupInProjectUnits = default,
    Dictionary<IGItemGroupInProjectUnitId<TValue>, IGItemGroupInProjectUnit<TValue>> gItemGroupInProjectUnits = default,
    Dictionary<IGResourceUnitId<TValue>, IGResourceUnit<TValue>> gResourceUnits = default,
    IGPatternReplacement gPatternReplacement = default,
    IGComment gComment = default

    ) {
      GName = gName == default ? "" : gName;
      GRelativePath = gRelativePath == default ? "" : gRelativePath;
      GFileSuffix = gFileSuffix == default ? ".csproj" : gFileSuffix;
      GPropertyGroupInProjectUnits = gPropertyGroupInProjectUnits == default ? new Dictionary<IGPropertyGroupInProjectUnitId<TValue>, IGPropertyGroupInProjectUnit<TValue>>() : gPropertyGroupInProjectUnits;
      GItemGroupInProjectUnits = gItemGroupInProjectUnits == default ? new Dictionary<IGItemGroupInProjectUnitId<TValue>, IGItemGroupInProjectUnit<TValue>>() : gItemGroupInProjectUnits;
      GResourceUnits = gResourceUnits == default ? new Dictionary<IGResourceUnitId<TValue>, IGResourceUnit<TValue>>() : gResourceUnits;
      GPatternReplacement = gPatternReplacement == default ? new GPatternReplacement() : gPatternReplacement;
      GComment = gComment == default ? new GComment() : gComment;
      Id = new GProjectUnitId<TValue>();
    }

    public string GName { get; init; }
    public string GRelativePath { get; init; }
    public string GFileSuffix { get; init; }
    public Dictionary<IGResourceUnitId<TValue>, IGResourceUnit<TValue>> GResourceUnits { get; init; }
    public Dictionary<IGPropertyGroupInProjectUnitId<TValue>, IGPropertyGroupInProjectUnit<TValue>> GPropertyGroupInProjectUnits { get; init; }
    public Dictionary<IGItemGroupInProjectUnitId<TValue>, IGItemGroupInProjectUnit<TValue>> GItemGroupInProjectUnits { get; init; }
    public IGPatternReplacement GPatternReplacement { get; init; }
    public IGComment GComment { get; init; }
    public  IGProjectUnitId Id { get; init; }
    public static string Header { get; } = "<!--" + StringConstants.AutoGeneratedHeaderCommentTextStringDefault + " -->";
  }
}








