using System;
using System.Collections.Generic;
using System.Text;
using ATAP.Utilities.Philote;

namespace ATAP.Utilities.GenerateProgram {
  public record GResourceUnit : IGResourceUnit {
    public GResourceUnit(string gName, string gRelativePath = default, string gFileSuffix = default,
      Dictionary<IPhilote<IGResourceItem>, IGResourceItem> gResourceItems = default,
      IGPatternReplacement gPatternReplacement = default,
      IGComment gComment = default
    ) {
      GName = gName ?? throw new ArgumentNullException(nameof(gName));
      GRelativePath = gRelativePath == default ? "Resources" : gRelativePath;
      GFileSuffix = gFileSuffix == default ? ".resx" : gFileSuffix;
      GResourceItems = gResourceItems == default ? new Dictionary<Philote<GResourceItem>, GResourceItem>() : gResourceItems;
      GPatternReplacement = gPatternReplacement == default ? new GPatternReplacement() : gPatternReplacement;
      GComment = gComment == default ? new GComment() : gComment;
      Philote = new Philote<GResourceUnit>();
    }

    public string GName { get; init; }
    public string GRelativePath { get; init; }
    public string GFileSuffix { get; init; }
    public Dictionary<IPhilote<IGResourceItem>, IGResourceItem> GResourceItems { get; init; }
    public IGPatternReplacement GPatternReplacement { get; init; }
    public IGComment GComment { get; init; }
    public IPhilote<IGResourceUnit> Philote { get; init; }
    public static string Header { get; } = "<!-- " + StringConstants.AutoGeneratedHeaderCommentTextStringDefault + " -->";
  }
}

