<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <IsPackable>true</IsPackable>
    <!-- Assembly, File, and Package Information for this assembly-->
    <!-- Build and revision are created based on date-->
    <MajorVersion>0</MajorVersion>
    <MinorVersion>1</MinorVersion>
    <PatchVersion>0</PatchVersion>
    <!-- Current Lifecycle stage for this assembly-->
    <PackageLifeCycleStage>Development</PackageLifeCycleStage>
    <!-- NuGet Package Label for the Nuget Package if the LifeCyclestage is not Production-->
    <PackageLabel>Alpha</PackageLabel>
    <Authors>ATAP</Authors>
    <Description>Defines the IConfigurationSecrets interface and aggregates the ATAP.Utilities.Configuration.Secrets.Shims package.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MethodBoundaryAspect.Fody" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <ProjectReference Include="..\..\ATAP.Utilities.ETW\ATAP.Utilities.ETW.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="FodyWeavers.xml" />
  </ItemGroup>

  <!-- Exclude child project source files from this project's compile glob -->
  <ItemGroup>
    <Compile Remove="Shims\**" />
  </ItemGroup>

  <!-- Aggregate the Shims package -->
  <ItemGroup>
    <ProjectReference Include="Shims\ATAP.Utilities.Configuration.Secrets.Shims.csproj" />
    <ProjectReference Include="..\..\ATAP.Utilities.Secrets\Interfaces\ATAP.Utilities.Secrets.Interfaces.csproj" />
  </ItemGroup>

</Project>
