<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <IsPackable>true</IsPackable>
    <Description>Defines the IConfigurationSecrets interface and aggregates the ATAP.Utilities.Configuration.Secrets.Shims package.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>

  <!-- Exclude child project source files from this project's compile glob -->
  <ItemGroup>
    <Compile Remove="Shims\**" />
  </ItemGroup>

  <!-- Aggregate the Shims package -->
  <ItemGroup>
    <ProjectReference Include="Shims\ATAP.Utilities.Configuration.Secrets.Shims.csproj" />
    <ProjectReference Include="..\..\ATAP.Utilities.Secrets\Interfaces\ATAP.Utilities.Secrets.Interfaces.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="FodyWeavers.xml" />
  </ItemGroup>

    <!-- Packages and projects to implement IL Weaving using Fody during the build process -->
  <ItemGroup>
    <!-- Project Reference to the ETW attribute and log provider -->
    <ProjectReference Include="..\ATAP.Utilities.ETW\ATAP.Utilities.ETW.csproj" />
  </ItemGroup>

</Project>
