

# --- Connection (unencrypted, per your constraint)
# the following is needed for connecting to the SQL server with a untrusted SSL certificate
flyway.url=jdbc:sqlserver://utat022;Initial Catalog=BuildSets;Integrated Security=True;Trusted_Connection=True;Encrypt=False;
flyway.user=FlywayAsBuildSetsDBOwner
flyway.password=ChangeMe_!234

# --- Locations for SQL migrations
flyway.locations=filesystem:./sql; ../../_shared/sql;

# Where SQL Server will read CSVs during BULK INSERT
flyway.placeholders.data_dir=C:\\Dropbox\\whertzing\\GitHub\\ATAP.Utilities\\Databases\\BuildSets\\Flyway\\DATA


# --- Where to put the history table (default schema dbo)
flyway.schemas=dbo

# --- Safety
flyway.cleanDisabled=true

# --- Idempotence
# (Not required, but recommended defaults)
flyway.outOfOrder=false
flyway.validateOnMigrate=true
flyway.validateMigrationNaming=true
