

# --- Connection (unencrypted, per your constraint)
# the following is needed for connecting to the SQL server with a untrusted SSL certificate
flyway.url=jdbc:sqlserver://utat022;databaseName=BuildSets;Encrypt=False;
flyway.user=FlywayAsBuildSetsDBOwner
flyway.password=ChangeMe_!234

# --- Locations for SQL migrations
flyway.locations=filesystem:./sql, ../../_shared/sql;

# Where SQL Server will read CSVs during BULK INSERT
flyway.placeholders.data_dir=C:\\Dropbox\\whertzing\\GitHub\\ATAP.Utilities\\Databases\\BuildSets\\Flyway\\DATA


# --- Where to put the history table (default schema dbo)
flyway.schemas=dbo

# --- Safety
flyway.cleanDisabled=true

# --- Idempotence
# (Not required, but recommended defaults)
flyway.outOfOrder=false
flyway.validateOnMigrate=true
flyway.validateMigrationNaming=true

#  -- placeholders for manifest. Actual values at runtime will be placed in Env variables or command line overrides
flyway.placeholders.PackageName=BuildSets.Functions
flyway.placeholders.PackageVersion=0.0.00008
flyway.placeholders.GitTag=v0.0.00008
flyway.placeholders.GitCommit=abcdef1
flyway.placeholders.ManifestValues=(N'V00.01.000010__Init.sql','V',N'4d2...'),(N'R__Permissions.sql','R',N'9ab...')
