# ── PowerShellGet feed: powershellget-experimental ────────────────────
$global:configRootKeys.Add('ProGetFeedPowerShellExperimentalUriSchemeConfigRootKey', 'ProGetFeedPowerShellExperimentalUriScheme')
$global:configRootKeys.Add('ProGetFeedPowerShellExperimentalUriHostConfigRootKey', 'ProGetFeedPowerShellExperimentalUriHost')
$global:configRootKeys.Add('ProGetFeedPowerShellExperimentalUriPortConfigRootKey', 'ProGetFeedPowerShellExperimentalUriPort')
$global:configRootKeys.Add('ProGetFeedPowerShellExperimentalUriPathConfigRootKey', 'ProGetFeedPowerShellExperimentalUriPath')
$global:configRootKeys.Add('ProGetFeedPowerShellExperimentalUriQueryStringConfigRootKey', 'ProGetFeedPowerShellExperimentalUriQueryString')
$global:configRootKeys.Add('ProGetFeedPowerShellExperimentalUriConfigRootKey', 'ProGetFeedPowerShellExperimentalUri')
$global:configRootKeys.Add('ProGetFeedPowerShellExperimentalFeedNameConfigRootKey', 'ProGetFeedPowerShellExperimentalFeedName')
$global:configRootKeys.Add('ProGetFeedPowerShellExperimentalFeedTypeConfigRootKey', 'ProGetFeedPowerShellExperimentalFeedType')
$global:configRootKeys.Add('ProGetFeedPowerShellExperimentalApiKeyNameConfigRootKey', 'ProGetFeedPowerShellExperimentalApiKeyName')
$global:configRootKeys.Add('ProGetFeedPowerShellExperimentalFeedConfigRootKey', 'ProGetFeedPowerShellExperimental')

# ── PowerShellGet feed: powershellget-development ─────────────────────
$global:configRootKeys.Add('ProGetFeedPowerShellDevelopmentUriSchemeConfigRootKey', 'ProGetFeedPowerShellDevelopmentUriScheme')
$global:configRootKeys.Add('ProGetFeedPowerShellDevelopmentUriHostConfigRootKey', 'ProGetFeedPowerShellDevelopmentUriHost')
$global:configRootKeys.Add('ProGetFeedPowerShellDevelopmentUriPortConfigRootKey', 'ProGetFeedPowerShellDevelopmentUriPort')
$global:configRootKeys.Add('ProGetFeedPowerShellDevelopmentUriPathConfigRootKey', 'ProGetFeedPowerShellDevelopmentUriPath')
$global:configRootKeys.Add('ProGetFeedPowerShellDevelopmentUriQueryStringConfigRootKey', 'ProGetFeedPowerShellDevelopmentUriQueryString')
$global:configRootKeys.Add('ProGetFeedPowerShellDevelopmentUriConfigRootKey', 'ProGetFeedPowerShellDevelopmentUri')
$global:configRootKeys.Add('ProGetFeedPowerShellDevelopmentFeedNameConfigRootKey', 'ProGetFeedPowerShellDevelopmentFeedName')
$global:configRootKeys.Add('ProGetFeedPowerShellDevelopmentFeedTypeConfigRootKey', 'ProGetFeedPowerShellDevelopmentFeedType')
$global:configRootKeys.Add('ProGetFeedPowerShellDevelopmentApiKeyNameConfigRootKey', 'ProGetFeedPowerShellDevelopmentApiKeyName')
$global:configRootKeys.Add('ProGetFeedPowerShellDevelopmentFeedConfigRootKey', 'ProGetFeedPowerShellDevelopment')

# ── PowerShellGet feed: powershellget-testing ─────────────────────────
$global:configRootKeys.Add('ProGetFeedPowerShellTestingUriSchemeConfigRootKey', 'ProGetFeedPowerShellTestingUriScheme')
$global:configRootKeys.Add('ProGetFeedPowerShellTestingUriHostConfigRootKey', 'ProGetFeedPowerShellTestingUriHost')
$global:configRootKeys.Add('ProGetFeedPowerShellTestingUriPortConfigRootKey', 'ProGetFeedPowerShellTestingUriPort')
$global:configRootKeys.Add('ProGetFeedPowerShellTestingUriPathConfigRootKey', 'ProGetFeedPowerShellTestingUriPath')
$global:configRootKeys.Add('ProGetFeedPowerShellTestingUriQueryStringConfigRootKey', 'ProGetFeedPowerShellTestingUriQueryString')
$global:configRootKeys.Add('ProGetFeedPowerShellTestingUriConfigRootKey', 'ProGetFeedPowerShellTestingUri')
$global:configRootKeys.Add('ProGetFeedPowerShellTestingFeedNameConfigRootKey', 'ProGetFeedPowerShellTestingFeedName')
$global:configRootKeys.Add('ProGetFeedPowerShellTestingFeedTypeConfigRootKey', 'ProGetFeedPowerShellTestingFeedType')
$global:configRootKeys.Add('ProGetFeedPowerShellTestingApiKeyNameConfigRootKey', 'ProGetFeedPowerShellTestingApiKeyName')
$global:configRootKeys.Add('ProGetFeedPowerShellTestingFeedConfigRootKey', 'ProGetFeedPowerShellTesting')

# ── PowerShellGet feed: powershellget-production ──────────────────────
$global:configRootKeys.Add('ProGetFeedPowerShellProductionUriSchemeConfigRootKey', 'ProGetFeedPowerShellProductionUriScheme')
$global:configRootKeys.Add('ProGetFeedPowerShellProductionUriHostConfigRootKey', 'ProGetFeedPowerShellProductionUriHost')
$global:configRootKeys.Add('ProGetFeedPowerShellProductionUriPortConfigRootKey', 'ProGetFeedPowerShellProductionUriPort')
$global:configRootKeys.Add('ProGetFeedPowerShellProductionUriPathConfigRootKey', 'ProGetFeedPowerShellProductionUriPath')
$global:configRootKeys.Add('ProGetFeedPowerShellProductionUriQueryStringConfigRootKey', 'ProGetFeedPowerShellProductionUriQueryString')
$global:configRootKeys.Add('ProGetFeedPowerShellProductionUriConfigRootKey', 'ProGetFeedPowerShellProductionUri')
$global:configRootKeys.Add('ProGetFeedPowerShellProductionFeedNameConfigRootKey', 'ProGetFeedPowerShellProductionFeedName')
$global:configRootKeys.Add('ProGetFeedPowerShellProductionFeedTypeConfigRootKey', 'ProGetFeedPowerShellProductionFeedType')
$global:configRootKeys.Add('ProGetFeedPowerShellProductionApiKeyNameConfigRootKey', 'ProGetFeedPowerShellProductionApiKeyName')
$global:configRootKeys.Add('ProGetFeedPowerShellProductionFeedConfigRootKey', 'ProGetFeedPowerShellProduction')

# ── PowerShellGet feed: powershellget-integration ─────────────────────
$global:configRootKeys.Add('ProGetFeedPowerShellIntegrationUriSchemeConfigRootKey', 'ProGetFeedPowerShellIntegrationUriScheme')
$global:configRootKeys.Add('ProGetFeedPowerShellIntegrationUriHostConfigRootKey', 'ProGetFeedPowerShellIntegrationUriHost')
$global:configRootKeys.Add('ProGetFeedPowerShellIntegrationUriPortConfigRootKey', 'ProGetFeedPowerShellIntegrationUriPort')
$global:configRootKeys.Add('ProGetFeedPowerShellIntegrationUriPathConfigRootKey', 'ProGetFeedPowerShellIntegrationUriPath')
$global:configRootKeys.Add('ProGetFeedPowerShellIntegrationUriQueryStringConfigRootKey', 'ProGetFeedPowerShellIntegrationUriQueryString')
$global:configRootKeys.Add('ProGetFeedPowerShellIntegrationUriConfigRootKey', 'ProGetFeedPowerShellIntegrationUri')
$global:configRootKeys.Add('ProGetFeedPowerShellIntegrationFeedNameConfigRootKey', 'ProGetFeedPowerShellIntegrationFeedName')
$global:configRootKeys.Add('ProGetFeedPowerShellIntegrationFeedTypeConfigRootKey', 'ProGetFeedPowerShellIntegrationFeedType')
$global:configRootKeys.Add('ProGetFeedPowerShellIntegrationApiKeyNameConfigRootKey', 'ProGetFeedPowerShellIntegrationApiKeyName')
$global:configRootKeys.Add('ProGetFeedPowerShellIntegrationFeedConfigRootKey', 'ProGetFeedPowerShellIntegration')

# ── PowerShellGet feed: powershellget-qa ──────────────────────────────
$global:configRootKeys.Add('ProGetFeedPowerShellQAUriSchemeConfigRootKey', 'ProGetFeedPowerShellQAUriScheme')
$global:configRootKeys.Add('ProGetFeedPowerShellQAUriHostConfigRootKey', 'ProGetFeedPowerShellQAUriHost')
$global:configRootKeys.Add('ProGetFeedPowerShellQAUriPortConfigRootKey', 'ProGetFeedPowerShellQAUriPort')
$global:configRootKeys.Add('ProGetFeedPowerShellQAUriPathConfigRootKey', 'ProGetFeedPowerShellQAUriPath')
$global:configRootKeys.Add('ProGetFeedPowerShellQAUriQueryStringConfigRootKey', 'ProGetFeedPowerShellQAUriQueryString')
$global:configRootKeys.Add('ProGetFeedPowerShellQAUriConfigRootKey', 'ProGetFeedPowerShellQAUri')
$global:configRootKeys.Add('ProGetFeedPowerShellQAFeedNameConfigRootKey', 'ProGetFeedPowerShellQAFeedName')
$global:configRootKeys.Add('ProGetFeedPowerShellQAFeedTypeConfigRootKey', 'ProGetFeedPowerShellQAFeedType')
$global:configRootKeys.Add('ProGetFeedPowerShellQAApiKeyNameConfigRootKey', 'ProGetFeedPowerShellQAApiKeyName')
$global:configRootKeys.Add('ProGetFeedPowerShellQAFeedConfigRootKey', 'ProGetFeedPowerShellQA')

# ── PowerShellGet feed: powershellget-stable ──────────────────────────
$global:configRootKeys.Add('ProGetFeedPowerShellStableUriSchemeConfigRootKey', 'ProGetFeedPowerShellStableUriScheme')
$global:configRootKeys.Add('ProGetFeedPowerShellStableUriHostConfigRootKey', 'ProGetFeedPowerShellStableUriHost')
$global:configRootKeys.Add('ProGetFeedPowerShellStableUriPortConfigRootKey', 'ProGetFeedPowerShellStableUriPort')
$global:configRootKeys.Add('ProGetFeedPowerShellStableUriPathConfigRootKey', 'ProGetFeedPowerShellStableUriPath')
$global:configRootKeys.Add('ProGetFeedPowerShellStableUriQueryStringConfigRootKey', 'ProGetFeedPowerShellStableUriQueryString')
$global:configRootKeys.Add('ProGetFeedPowerShellStableUriConfigRootKey', 'ProGetFeedPowerShellStableUri')
$global:configRootKeys.Add('ProGetFeedPowerShellStableFeedNameConfigRootKey', 'ProGetFeedPowerShellStableFeedName')
$global:configRootKeys.Add('ProGetFeedPowerShellStableFeedTypeConfigRootKey', 'ProGetFeedPowerShellStableFeedType')
$global:configRootKeys.Add('ProGetFeedPowerShellStableApiKeyNameConfigRootKey', 'ProGetFeedPowerShellStableApiKeyName')
$global:configRootKeys.Add('ProGetFeedPowerShellStableFeedConfigRootKey', 'ProGetFeedPowerShellStable')
