
        # ── NuGet feed: nuget-experimental ───────────────────────────────────
        $global:configRootKeys.Add('ProGetFeedNuGetExperimentalUriSchemeConfigRootKey', 'ProGetFeedNuGetExperimentalUriScheme')
        $global:configRootKeys.Add('ProGetFeedNuGetExperimentalUriHostConfigRootKey', 'ProGetFeedNuGetExperimentalUriHost')
        $global:configRootKeys.Add('ProGetFeedNuGetExperimentalUriPortConfigRootKey', 'ProGetFeedNuGetExperimentalUriPort')
        $global:configRootKeys.Add('ProGetFeedNuGetExperimentalUriPathConfigRootKey', 'ProGetFeedNuGetExperimentalUriPath')
        $global:configRootKeys.Add('ProGetFeedNuGetExperimentalUriQueryStringConfigRootKey', 'ProGetFeedNuGetExperimentalUriQueryString')
        $global:configRootKeys.Add('ProGetFeedNuGetExperimentalUriConfigRootKey', 'ProGetFeedNuGetExperimentalUri')
        $global:configRootKeys.Add('ProGetFeedNuGetExperimentalFeedNameConfigRootKey', 'ProGetFeedNuGetExperimentalFeedName')
        $global:configRootKeys.Add('ProGetFeedNuGetExperimentalFeedTypeConfigRootKey', 'ProGetFeedNuGetExperimentalFeedType')
        $global:configRootKeys.Add('ProGetFeedNuGetExperimentalApiKeyNameConfigRootKey', 'ProGetFeedNuGetExperimentalApiKeyName')
        $global:configRootKeys.Add('ProGetFeedNuGetExperimentalFeedConfigRootKey', 'ProGetFeedNuGetExperimental')

        # ── NuGet feed: nuget-development ─────────────────────────────────────
        $global:configRootKeys.Add('ProGetFeedNuGetDevelopmentUriSchemeConfigRootKey', 'ProGetFeedNuGetDevelopmentUriScheme')
        $global:configRootKeys.Add('ProGetFeedNuGetDevelopmentUriHostConfigRootKey', 'ProGetFeedNuGetDevelopmentUriHost')
        $global:configRootKeys.Add('ProGetFeedNuGetDevelopmentUriPortConfigRootKey', 'ProGetFeedNuGetDevelopmentUriPort')
        $global:configRootKeys.Add('ProGetFeedNuGetDevelopmentUriPathConfigRootKey', 'ProGetFeedNuGetDevelopmentUriPath')
        $global:configRootKeys.Add('ProGetFeedNuGetDevelopmentUriQueryStringConfigRootKey', 'ProGetFeedNuGetDevelopmentUriQueryString')
        $global:configRootKeys.Add('ProGetFeedNuGetDevelopmentUriConfigRootKey', 'ProGetFeedNuGetDevelopmentUri')
        $global:configRootKeys.Add('ProGetFeedNuGetDevelopmentFeedNameConfigRootKey', 'ProGetFeedNuGetDevelopmentFeedName')
        $global:configRootKeys.Add('ProGetFeedNuGetDevelopmentFeedTypeConfigRootKey', 'ProGetFeedNuGetDevelopmentFeedType')
        $global:configRootKeys.Add('ProGetFeedNuGetDevelopmentApiKeyNameConfigRootKey', 'ProGetFeedNuGetDevelopmentApiKeyName')
        $global:configRootKeys.Add('ProGetFeedNuGetDevelopmentFeedConfigRootKey', 'ProGetFeedNuGetDevelopment')

        # ── NuGet feed: nuget-testing ─────────────────────────────────────────
        $global:configRootKeys.Add('ProGetFeedNuGetTestingUriSchemeConfigRootKey', 'ProGetFeedNuGetTestingUriScheme')
        $global:configRootKeys.Add('ProGetFeedNuGetTestingUriHostConfigRootKey', 'ProGetFeedNuGetTestingUriHost')
        $global:configRootKeys.Add('ProGetFeedNuGetTestingUriPortConfigRootKey', 'ProGetFeedNuGetTestingUriPort')
        $global:configRootKeys.Add('ProGetFeedNuGetTestingUriPathConfigRootKey', 'ProGetFeedNuGetTestingUriPath')
        $global:configRootKeys.Add('ProGetFeedNuGetTestingUriQueryStringConfigRootKey', 'ProGetFeedNuGetTestingUriQueryString')
        $global:configRootKeys.Add('ProGetFeedNuGetTestingUriConfigRootKey', 'ProGetFeedNuGetTestingUri')
        $global:configRootKeys.Add('ProGetFeedNuGetTestingFeedNameConfigRootKey', 'ProGetFeedNuGetTestingFeedName')
        $global:configRootKeys.Add('ProGetFeedNuGetTestingFeedTypeConfigRootKey', 'ProGetFeedNuGetTestingFeedType')
        $global:configRootKeys.Add('ProGetFeedNuGetTestingApiKeyNameConfigRootKey', 'ProGetFeedNuGetTestingApiKeyName')
        $global:configRootKeys.Add('ProGetFeedNuGetTestingFeedConfigRootKey', 'ProGetFeedNuGetTesting')

        # ── NuGet feed: nuget-production ──────────────────────────────────────
        $global:configRootKeys.Add('ProGetFeedNuGetProductionUriSchemeConfigRootKey', 'ProGetFeedNuGetProductionUriScheme')
        $global:configRootKeys.Add('ProGetFeedNuGetProductionUriHostConfigRootKey', 'ProGetFeedNuGetProductionUriHost')
        $global:configRootKeys.Add('ProGetFeedNuGetProductionUriPortConfigRootKey', 'ProGetFeedNuGetProductionUriPort')
        $global:configRootKeys.Add('ProGetFeedNuGetProductionUriPathConfigRootKey', 'ProGetFeedNuGetProductionUriPath')
        $global:configRootKeys.Add('ProGetFeedNuGetProductionUriQueryStringConfigRootKey', 'ProGetFeedNuGetProductionUriQueryString')
        $global:configRootKeys.Add('ProGetFeedNuGetProductionUriConfigRootKey', 'ProGetFeedNuGetProductionUri')
        $global:configRootKeys.Add('ProGetFeedNuGetProductionFeedNameConfigRootKey', 'ProGetFeedNuGetProductionFeedName')
        $global:configRootKeys.Add('ProGetFeedNuGetProductionFeedTypeConfigRootKey', 'ProGetFeedNuGetProductionFeedType')
        $global:configRootKeys.Add('ProGetFeedNuGetProductionApiKeyNameConfigRootKey', 'ProGetFeedNuGetProductionApiKeyName')
        $global:configRootKeys.Add('ProGetFeedNuGetProductionFeedConfigRootKey', 'ProGetFeedNuGetProduction')

        # ── NuGet feed: nuget-integration ─────────────────────────────────────
        $global:configRootKeys.Add('ProGetFeedNuGetIntegrationUriSchemeConfigRootKey', 'ProGetFeedNuGetIntegrationUriScheme')
        $global:configRootKeys.Add('ProGetFeedNuGetIntegrationUriHostConfigRootKey', 'ProGetFeedNuGetIntegrationUriHost')
        $global:configRootKeys.Add('ProGetFeedNuGetIntegrationUriPortConfigRootKey', 'ProGetFeedNuGetIntegrationUriPort')
        $global:configRootKeys.Add('ProGetFeedNuGetIntegrationUriPathConfigRootKey', 'ProGetFeedNuGetIntegrationUriPath')
        $global:configRootKeys.Add('ProGetFeedNuGetIntegrationUriQueryStringConfigRootKey', 'ProGetFeedNuGetIntegrationUriQueryString')
        $global:configRootKeys.Add('ProGetFeedNuGetIntegrationUriConfigRootKey', 'ProGetFeedNuGetIntegrationUri')
        $global:configRootKeys.Add('ProGetFeedNuGetIntegrationFeedNameConfigRootKey', 'ProGetFeedNuGetIntegrationFeedName')
        $global:configRootKeys.Add('ProGetFeedNuGetIntegrationFeedTypeConfigRootKey', 'ProGetFeedNuGetIntegrationFeedType')
        $global:configRootKeys.Add('ProGetFeedNuGetIntegrationApiKeyNameConfigRootKey', 'ProGetFeedNuGetIntegrationApiKeyName')
        $global:configRootKeys.Add('ProGetFeedNuGetIntegrationFeedConfigRootKey', 'ProGetFeedNuGetIntegration')

        # ── NuGet feed: nuget-qa ──────────────────────────────────────────────
        $global:configRootKeys.Add('ProGetFeedNuGetQAUriSchemeConfigRootKey', 'ProGetFeedNuGetQAUriScheme')
        $global:configRootKeys.Add('ProGetFeedNuGetQAUriHostConfigRootKey', 'ProGetFeedNuGetQAUriHost')
        $global:configRootKeys.Add('ProGetFeedNuGetQAUriPortConfigRootKey', 'ProGetFeedNuGetQAUriPort')
        $global:configRootKeys.Add('ProGetFeedNuGetQAUriPathConfigRootKey', 'ProGetFeedNuGetQAUriPath')
        $global:configRootKeys.Add('ProGetFeedNuGetQAUriQueryStringConfigRootKey', 'ProGetFeedNuGetQAUriQueryString')
        $global:configRootKeys.Add('ProGetFeedNuGetQAUriConfigRootKey', 'ProGetFeedNuGetQAUri')
        $global:configRootKeys.Add('ProGetFeedNuGetQAFeedNameConfigRootKey', 'ProGetFeedNuGetQAFeedName')
        $global:configRootKeys.Add('ProGetFeedNuGetQAFeedTypeConfigRootKey', 'ProGetFeedNuGetQAFeedType')
        $global:configRootKeys.Add('ProGetFeedNuGetQAApiKeyNameConfigRootKey', 'ProGetFeedNuGetQAApiKeyName')
        $global:configRootKeys.Add('ProGetFeedNuGetQAFeedConfigRootKey', 'ProGetFeedNuGetQA')

        # ── NuGet feed: nuget-stable ──────────────────────────────────────────
        $global:configRootKeys.Add('ProGetFeedNuGetStableUriSchemeConfigRootKey', 'ProGetFeedNuGetStableUriScheme')
        $global:configRootKeys.Add('ProGetFeedNuGetStableUriHostConfigRootKey', 'ProGetFeedNuGetStableUriHost')
        $global:configRootKeys.Add('ProGetFeedNuGetStableUriPortConfigRootKey', 'ProGetFeedNuGetStableUriPort')
        $global:configRootKeys.Add('ProGetFeedNuGetStableUriPathConfigRootKey', 'ProGetFeedNuGetStableUriPath')
        $global:configRootKeys.Add('ProGetFeedNuGetStableUriQueryStringConfigRootKey', 'ProGetFeedNuGetStableUriQueryString')
        $global:configRootKeys.Add('ProGetFeedNuGetStableUriConfigRootKey', 'ProGetFeedNuGetStableUri')
        $global:configRootKeys.Add('ProGetFeedNuGetStableFeedNameConfigRootKey', 'ProGetFeedNuGetStableFeedName')
        $global:configRootKeys.Add('ProGetFeedNuGetStableFeedTypeConfigRootKey', 'ProGetFeedNuGetStableFeedType')
        $global:configRootKeys.Add('ProGetFeedNuGetStableApiKeyNameConfigRootKey', 'ProGetFeedNuGetStableApiKeyName')
        $global:configRootKeys.Add('ProGetFeedNuGetStableFeedConfigRootKey', 'ProGetFeedNuGetStable')
