<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
  </PropertyGroup>
  <ItemGroup>
    <Content Remove="../../tests/xunit.runner.json" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\src\ATAP.Utilities.ETW\ATAP.Utilities.ETW.csproj" />
  </ItemGroup>
</Project>
