using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GenerateProgram {
  public static class StringConstants {
    public const string HeaderTextStringDefault = @"// Autogenerated FIle. Any changes you make here will be overwritten the next time this file is generated.";
  }
}
