using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GenerateProgram {
  public static class StringConstants {
    public const string assemblyNameReplacementPattern = "AssemblyNameReplacementPattern";
    public const string AutoGeneratedHeaderCommentTextStringDefault = @" Autogenerated File. Any changes you make here will be overwritten the next time this file is generated.";
    public const string ProjectUnitSDKProjectStartTagStringDefault  =@"<Project Sdk=""Microsoft.NET.Sdk"">";
    public const string ProjectUnitSDKProjectEndTagStringDefault  =@"</Project>";
  }
}
