<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Interfaces\ATAP.Utilities.Secrets.Interfaces.csproj" />
    <ProjectReference Include="..\..\StringConstants\ATAP.Utilities.Secrets.StringConstants.csproj" />
    <ProjectReference Include="..\..\..\ATAP.Utilities.Plugin\Model\ATAP.Utilities.Plugin.Model.csproj" />
    <ProjectReference Include="..\..\..\ATAP.Utilities.Loader\Interfaces\ATAP.Utilities.Loader.Interfaces.csproj" />
    <ProjectReference Include="..\..\..\ATAP.Utilities.Loader\Model\ATAP.Utilities.Loader.Model.csproj" />
    <ProjectReference Include="..\..\..\ATAP.Utilities.FIleIO\ATAP.Utilities.FileIO.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>

  <!-- Packages and projects to implement IL Weaving using Fody during the build process -->
  <ItemGroup>
    <ProjectReference Include="..\..\..\ATAP.Utilities.ETW\ATAP.Utilities.ETW.csproj" />
  </ItemGroup>

</Project>
